### ISSUE TITLE
screencast: pipewire 0.3 support

### ISSUE THREAD

**Issue by danshick** [emersion/xdg-desktop-portal-wlr#10]
Screencast code will need rework for API changes in Pipewire 0.3.

[PR](https://gitlab.gnome.org/GNOME/mutter/merge_requests/1006#10194861d1fd363d5705e4a5788c5ea79a253490) for Mutter supporting Pipewire 0.3

**Comment by braderhart** [comment]
Pipewire 0.3 is out now

**Comment by danshick** [comment]
Yeah, ive been following @wtay on IRC and saw this land. Plan is to focus on finishing the cleanup for 0.2 and then backport the fixes. This issue should be relatively easy to close once that's done. Sadly, it looks like 0.3 isn't backwards compatible with 0.2 producers.
