### ISSUE TITLE
Broken EnumFormat object when format is without alpha

### ISSUE THREAD

**Issue by st3r4g** [emersion/xdg-desktop-portal-wlr#102]
Possible issue at lines:
https://github.com/emersion/xdg-desktop-portal-wlr/blob/master/src/screencast/pipewire_screencast.c#L178-L179
the size of the enum doesn't match the number of elements. But I don't know if it's valid API and thus a pipewire server/library bug.

`pw-cli` shows (notice truncated output):
```
  Object: size 96, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
    Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
      Id 2        (Spa:Enum:MediaType:video)
    Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
      Id 1        (Spa:Enum:MediaSubtype:raw)
    Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
      Choice: type Spa:Enum:Choice:Enum, flags 00000000 24 4
        Id 7        (Spa:Enum:VideoFormat:RGBx)
        Id 7        (Spa:Enum:VideoFormat:RGBx)
```

And the screencast doesn't work. This is with:
```
wlroots master
xdg-desktop-portal-wlr-0.2.0
pipewire-0.3.23
```

Previous discussion: https://github.com/swaywm/wlroots/issues/2784

**Comment by st3r4g** [comment]
Having for example `SPA_POD_CHOICE_ENUM_Id(2, format, format)` fixes the screencast.

**Comment by emersion** [comment]
Hm, as always macro magic makes this difficult to understand. Maybe we can store the result of `SPA_POD_CHOICE_ENUM_Id` in an intermediate variable instead of doing the `nformats` logic.

**Comment by st3r4g** [comment]
In the pipewire sources, `SPA_POD_CHOICE_ENUM_Id` is always used with a number of elements known at compile time. Giving `n_vals` != from the actual value count looks like wrong usage, and there is no safety check. Building this object is dangerous...

Given the dynamic number of formats, maybe here it's better to build the pod line by line with `spa_pod_builder_add` instead of the convenience macro?

**Comment by emersion** [comment]
Alternatively, is it a big deal if we expose the same format twice?

**Comment by danshick** [comment]
I think we're just off by one. The args for that macro (IIRC) are "count", "default", "option_1", ..., "option_n". We start at 1, increment for the non-alpha, and then add 1 again in the macro for a total of 3 when there are actually just two formats with a default.

I don't think we're hitting the case where the pixelformat is invalid. If we were, even though it is computed dynamically, we'd have bigger issues that I don't think could be resolved by hardcoding.

**Comment by st3r4g** [comment]
> I think we're just off by one. The args for that macro (IIRC) are "count", "default", "option_1", ..., "option_n". We start at 1, increment for the non-alpha, and then add 1 again in the macro for a total of 3 when there are actually just two formats with a default.

I don't think so... Look here:
https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/spa/plugins/videotestsrc/videotestsrc.c#L481-484
The default is included in the count.

> I don't think we're hitting the case where the pixelformat is invalid.
imo the problem is that n_vals != from the actual value count in `SPA_POD_CHOICE_ENUM_Id` (which only happens in the without alpha case) builds a malformed spa object.

**Comment by emersion** [comment]
The point is, we always provide 3 values, so we should hardcode 3 instead of the current `n_formats` logic.

**Comment by st3r4g** [comment]
> The point is, we always provide 3 values, so we should hardcode 3 instead of the current `n_formats` logic.

that would make the EnumFormat object well formed, yes, but I don't really like that when format is without alpha you end up sending an unknown format or the same format twice...

**Comment by emersion** [comment]
We would send the same format twice, which isn't too bad.

**Comment by st3r4g** [comment]
> We would send the same format twice, which isn't too bad.

maybe, but I'd like to do it cleanly. I'll try how it looks if we expand `spa_pod_builder_add_object` and send a PR, then we can decide.

**Comment by danshick** [comment]
Thanks for this investigation and for keeping me honest. You can tell I last touched this a while ago and I'm having to relearn how these macros work for this conversation. Your PR looks good so far and I think we can move the discussion there.

Thanks.
