### ISSUE TITLE
iniparser-4 fails to be found by meson

### ISSUE THREAD

**Issue by prometheanfire** [emersion/xdg-desktop-portal-wlr#106]
`meson.build:29:0: ERROR: C shared or static library 'iniparser' not found`

downstream bug here https://bugs.gentoo.org/777738

**Comment by emersion** [comment]
Somewhat related: https://github.com/emersion/xdg-desktop-portal-wlr/issues/96

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/xdg-desktop-portal-wlr/pull/126
