### ISSUE TITLE
Failed to start as systemd unit

### ISSUE THREAD

**Issue by ael-code** [emersion/xdg-desktop-portal-wlr#116]
Hi everyone and thanks for this indispensable project!

Recently I'm experiencing problem starting `xdg-desktop-portal-wlr` as systemd unit. I'm on Arch linux with the following package versions:

- xdg-desktop-portal-wlr: `0.3.0-1`
- pipewire: `1:0.3.25-1`
- pipewire-media-session: `1:0.3.25-1`
- sway: `1:1.6-1`
- wlroots: `0.13.0-1`

When I try to start the systemd unit, with TRACE log level, I get the following error:
```
Apr 21 08:09:53 X1C xdg-desktop-portal-wlr[3321]: 2021/04/21 08:09:53 [TRACE] - config: trying config file /home/ael/.config/xdg-desktop-portal-wlr/config
Apr 21 08:09:53 X1C xdg-desktop-portal-wlr[3321]: 2021/04/21 08:09:53 [INFO] - config: using config file /home/ael/.config/xdg-desktop-portal-wlr/config
Apr 21 08:09:53 X1C xdg-desktop-portal-wlr[3321]: 2021/04/21 08:09:53 [DEBUG] - config: config file parsed
Apr 21 08:09:53 X1C xdg-desktop-portal-wlr[3321]: 2021/04/21 08:09:53 [DEBUG] - config: outputname  (null)
Apr 21 08:09:53 X1C xdg-desktop-portal-wlr[3321]: 2021/04/21 08:09:53 [DEBUG] - config: chooser_cmd: (null)
Apr 21 08:09:53 X1C xdg-desktop-portal-wlr[3321]: 2021/04/21 08:09:53 [DEBUG] - config: chooser_type: none
Apr 21 08:09:53 X1C xdg-desktop-portal-wlr[3321]: 2021/04/21 08:09:53 [DEBUG] - dbus: connected
Apr 21 08:09:53 X1C xdg-desktop-portal-wlr[3321]: 2021/04/21 08:09:53 [ERROR] - wayland: failed to connect to display
Apr 21 08:09:53 X1C systemd[1490]: xdg-desktop-portal-wlr.service: Main process exited, code=exited, status=1/FAILURE
Apr 21 08:09:53 X1C systemd[1490]: xdg-desktop-portal-wlr.service: Failed with result 'exit-code'.
Apr 21 08:09:53 X1C systemd[1490]: Failed to start Portal service (wlroots implementation).
```

While if I start it directly using `/usr/lib/xdg-desktop-portal-wlr -l TRACE` from the terminal it will works fine.

I guess there is something in the environment of the systemd unit that is preventing it to start properly. The real problem here is that `xdg-desktop-portal-wlr` **doesn't provide any useful error information** except `wayland: failed to connect to display` so I really don't know what is the reason of the failure.

Would it be possible to improve the returned failure message to add some additional info on the error?

**Comment by emersion** [comment]
"failed to connect to display" is as good of an error message as you're going to get. It can mean that WAYLAND_DISPLAY is not properly set, or that a Wayland compositor isn't running.

**Comment by toto-dev** [comment]
Thanks @emersion, you are right, in fact I managed to reproduce the failure from the terminal by removing the following variable from the environment:
```
WAYLAND_DISPLAY=wayland-1
```
Do you know who sets this variable and could I pass it to systemd ?

**Comment by emersion** [comment]
The compositor sets the variable. See item (4) of https://github.com/emersion/xdg-desktop-portal-wlr/wiki/%22It-doesn't-work%22-Troubleshooting-Checklist.

**Comment by ael-code** [comment]
For posterity I've solved the problem by adding:
```
exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY
```
To my sway configuration

**Comment by ael-code** [comment]
@emersion do you think it is feasible to improve the error message in the case the WAYLAND_DISPLAY env variable is missing?

**Comment by emersion** [comment]
I think we should have a safe-guard to require `WAYLAND_DISPLAY` in the systemd unit: https://github.com/emersion/mako/blob/e5b5d56aaaf8390c97a17c208f950803538e7294/contrib/systemd/mako.service#L7

**Comment by danshick** [comment]
@emersion certainly can't hurt. Ive never used this systemd option before. Will it give clear log messages as to the issue?

This also won't help us with `XDG_CURRENT_DESKTOP` but if it improves the log situation, maybe it is a suggestion we could make upstream?
