### ISSUE TITLE
Screenshot: Implement PickColor method

### ISSUE THREAD

**Issue by junglerobba** [emersion/xdg-desktop-portal-wlr#129]
https://github.com/flatpak/xdg-desktop-portal/commit/7f693a7d3918e193488746ccc012588c487363d6

This was already mentioned in some comments, but there was no separate issue for this yet.

**Comment by emersion** [comment]
slurp's -p mode can be used for this. From grim's README: `grim -g "$(slurp -p)" -t ppm -` will give a single pixel in an easy-to-parse format.
