### ISSUE TITLE
[Question] Are there plans to support more of the XDG Portal specification?

### ISSUE THREAD

**Issue by Diegovsky** [emersion/xdg-desktop-portal-wlr#135]
Since screencast and screenshot have the ability to use a graphic chooser (#59) are there plans to implement more of the XDG Portal implementation? (like FileChooser, Notification, etc)

**Comment by emersion** [comment]
Nope. These don't need any special interaction with the compositor.

**Comment by danshick** [comment]
It is important to note that you can install multiple portals and other implementations (gtk, kde, etc.) will act as a fallback for what we don't implement.

**Comment by languitar** [comment]
At least for the GTK portal implementation there are ongoing discussions whether it is viable/wanted to launch at all in a non-gnome context (https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/74 and https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/merge_requests/78). Moreover, there's an open PR for xdg-desktop-portal that might also render some of the currently used fallback logic unusable (https://github.com/flatpak/xdg-desktop-portal/pull/985). I am not sure if the current way of only selectively providing a few parts of the spec will continue to work in the future.

**Comment by emersion** [comment]
xdp-gnome is different from xdp-gtk.

**Comment by languitar** [comment]
Oh, you are right. Then the current fallback only depends on xdg-desktop-portal-gtk not declaring any required desktop.
