### ISSUE TITLE
Proposal: import buffers from pipewire

### ISSUE THREAD

**Issue by columbarius** [emersion/xdg-desktop-portal-wlr#137]
Currently we allocate a buffer, send it to wlroots for screencopy and then copy it onto the pipewire buffer when requested.

I would like to use the pipewire buffer chain directly. This means:
* using the add_buffer methods to allocate buffers
* using the pipewire on_process method as the main driver with the following process flow:
  * import pw_buffer to xdpw_simplebuffer
  * request screencopy for that buffer
  * export the xdpw_simplebuffer to pw_buffer
  * repeat
 
This might make screencopy_with_damage more inefficient, but i think when we want to drop the memcpy of shm buffers and only send fd's to the buffer around, we have to use more than one buffer to avoid race conditions.

**Comment by columbarius** [comment]
> Can we completely replace MemPtr with MemFd and let PipeWire do the conversion for clients that expect MemPtr?

afaik yes. Otherwise we would have to do one mmap after the allocation, which would not be too bad. Otherwise we can get the fd from a MemPtr pw_buffer, so no problem there.

**Comment by danshick** [comment]
I know that wlroots is no longer y-inverting frames, but can we be sure we won't ever need to do any bit-fiddling again for other compositors or strange graphics cards? That's the only reason I can think to leave MemPtr around as a legacy option long term. I don't think pipewire has any concept of y-inversion or similar.

I would like to be able to do zero frame processing in xdpw, so I support this idea in principle.

**Comment by emersion** [comment]
> I don't think pipewire has any concept of y-inversion or similar.

In theory PipeWire has negative strides for this. But clients don't support it.

We could just y-invert the buffer in-place if we want, before handing it over to PipeWire.

**Comment by danshick** [comment]
> We could just y-invert the buffer in-place if we want, before handing it over to PipeWire.

Yeah, of course. Why didn't I think of that.

**Comment by columbarius** [comment]
> Otherwise we would have to do one mmap after the allocation, which would not be too bad. Otherwise we can get the fd from a MemPtr pw_buffer, so no problem there.

It doesn't work this way. When we allocate our own buffers, we are restricted to MemFd and DmaBuf. But most clients only handling MemPtr do use the MAP_BUFFERS flag, so pipewire does the mmapping. 

As far as i tested it (python script, obs, firefox) it worked without any problem.

**Comment by columbarius** [comment]
Should we move from wl_shm_formats to drm_formats as the common format?

**Comment by emersion** [comment]
I'd favor this. Newer `wl_shm_format`s come from `drm_fourcc.h` nowadays, so `drm_fourcc.h` is the authoritative list. `wl_shm_format` can be [trivially](https://github.com/swaywm/wlroots/blob/d0560e2597e79f0f25c0ad9fd6969eaf10fd5558/render/pixel_format.c#L44) converted to DRM format codes right before sending the format on the wire.

The switch doesn't necessarily needs to happen together with this issue though. As long as we only deal with shm buffers, there's no real upside to switching to DRM format codes.

**Comment by columbarius** [comment]
Ok updated: I forgot that pipewire has only timers, so we could drive the screencopy only on a fixed framerate. I don't like that idea, so i'm still using wlroots to drive the chain.

**Comment by danshick** [comment]
Yup, they're built for fixed framerate even though they support variable with the framerate param set to 0. All of the examples are fixed framerate too. I think variable makes more sense for us, especially with damage.
