### ISSUE TITLE
Slurp display picker opens twice

### ISSUE THREAD

**Issue by sentriz** [emersion/xdg-desktop-portal-wlr#146]
Hi, when selecting a display to use before sharing, slurp asks me to pick a display twice
it seems to be one for the preview, then one for the actual sharing. 
I am wondering is this intentional?

(please see the video with two crosshair cursors)
thanks!

https://user-images.githubusercontent.com/6832539/121808957-d5209900-cc52-11eb-96b7-30311eb2fc46.mp4

**Comment by columbarius** [comment]
Hi, that's the behaviour on all chromium based browsers. 
Chromium insists to present it's own screenchooser with a preview, so it queries a screencast for the preview and later one for the real screencast. So you probably can pick another monitor the second time. 
Firefox just dropped it's chooser and presents the "use operating system settings". So you will only be queried once.

**Comment by sentriz** [comment]
makes sense, thanks :)
