### ISSUE TITLE
OBS not connecting portal

### ISSUE THREAD

**Issue by discover02** [emersion/xdg-desktop-portal-wlr#165]
Hi, I installed sway after upgrading my system to fedora 35. I installed xdg-desktop-portal-wlr. I edited ~/.config/xdg-desktop-portal-wlr. But obs doesn't work on sway at all. 

```
~/.config/xdg-desktop-portal-wlr
chooser-type=dmenu
chooser_cmd=wofi --show=dmenu
```

I tried Gnome and KDE. OBS works fine on them.

```
OBS output
error: Source ID 'pipewire-window-capture-source' not found
error: Failed to create source 'Window Capture (PipeWire)'!
error: Source ID 'pipewire-desktop-capture-source' not found
error: Failed to create source 'Screen Capture (PipeWire)'!
```

While on Fedora 34 obs was working fine on sway. How can I fix this problem? Thanks.

**Comment by 616b2f** [comment]
could this be the route cause for your issue: #168 ? In fedora 35 wireplumber is used as pipewire session manager.

**Comment by columbarius** [comment]
Is this fixed with the new release?

**Comment by 616b2f** [comment]
Yes, if it's the same issue, it should be solved, the new release is also on stable in fedora 35, so just update and try :)

**Comment by SPRATAY** [comment]
hey, but what if i have Screen Capture (PipeWire), but not Window Capture (PipeWire)?
i use gentoo

**Comment by columbarius** [comment]
@SPRATAY Window Capture is currently not supported. The closest you can currently get is sharing a fixed region of your screen with #156.

**Comment by columbarius** [comment]
I assume this issue was fixed with the new release. Please reopen if this problem remains.

**Comment by SPRATAY** [comment]
> 

I instal no result

**Comment by columbarius** [comment]
> > I assume this issue was fixed with the new release. Please reopen if this problem remains.

This was related to the opening issue.

> I 5.0 instal no result

There is no Window Capture in xdg-desktop-portal-wlr. This needs some work in wlroots first.

**Comment by SPRATAY** [comment]
> > > I assume this issue was fixed with the new release. Please reopen if this problem remains.
> 
> This was related to the opening issue.
> 
> > I 5.0 instal no result
> 
> There is no Window Capture in xdg-desktop-portal-wlr. This needs some work in wlroots first.

wait long?)
