### ISSUE TITLE
is it possible to get this working without systemd? on runit init system

### ISSUE THREAD

**Issue by ankkax** [emersion/xdg-desktop-portal-wlr#166]
I'm using artix with runit and swaywm, but can't get pipewire screen capture to work.
I tried with arch linux and it worked fine with xdg-desktop-portal-wlr but is it fully depended on systemd?

**Comment by SimplyCEO** [comment]
I am here to also confirm that it works. You just need to click wether you want to stream though, then it will immediately open the screenshare window.
