### ISSUE TITLE
Wireplumber interaction fails due of stream wrong id

### ISSUE THREAD

**Issue by thuck** [emersion/xdg-desktop-portal-wlr#168]
Screenshare is not working when using wireplumber instead of media-session.  
After the investigation with the wireplumber devs [87](https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/87); looks like the problem is the ID provided by wlr.  
There is a closed issue here #97 about this problem, but rolling back to media-session won't be an option in the future.  

From the dev of wireplumber:
`
right, this confirms it. 4294967295 is practically -1 wrapping around in an unsigned 32-bit integer, so the node id that is sent over D-Bus from the wlr portal to the script is in fact invalid.
`

**Comment by columbarius** [comment]
Could you try it with xdpw build from master? 5f5a29ccfdbd24e7efd874eb8317fb01e908a301 should have fixed that.

**Comment by thuck** [comment]
@columbarius just tested, it works fine using the master:
```
session /org/freedesktop/portal/desktop/session/1_3620/u1 created
sources selected
streams:
stream 114
```

**Comment by emersion** [comment]
Closing since this is fixed in master.

**Comment by 616b2f** [comment]
@emersion is there any timeline when this fix is released or hotfixed maybe? Because fedora 35 uses wireplumber now and screencasting does not work with the current release version

**Comment by columbarius** [comment]
Fedora has already backported that change.
It's probably in testing.
https://src.fedoraproject.org/rpms/xdg-desktop-portal-wlr/commits/rawhide

**Comment by emersion** [comment]
Released a new version with the fix: https://github.com/emersion/xdg-desktop-portal-wlr/releases/tag/v0.5.0
