### ISSUE TITLE
screencast: properly report cursor mode

### ISSUE THREAD

**Issue by danshick** [emersion/xdg-desktop-portal-wlr#18]
Should fix compatibility with obs-xdg-portal plugin per [this](https://gitlab.gnome.org/feaneron/obs-xdg-portal/-/issues/2).

Eventually, we should support all of these cursor modes properly, but for now it might be a good idea to allow this to be "fudged" with a CLI flag like we do with pixelformat, in case of compatibility issues.

**Comment by emersion** [comment]
The wlroots protocol supports Hidden and Embedded. We can set AvailableCursorModes to `0x1 | 0x2`.

**Comment by danshick** [comment]
We could probably even hack together mode 0x4 if we can retrieve the cursor position from wlroots. That's literally just "send me a location and a bitmap of a cursor" if I understand correctly.

**Comment by emersion** [comment]
We can't get neither the cursor position nor the cursor image.

**Comment by danshick** [comment]
Huh, okay. Guess i had assumed those would be easy.
