### ISSUE TITLE
screencast: unable to use screencapture a second time on firefox

### ISSUE THREAD

**Issue by columbarius** [emersion/xdg-desktop-portal-wlr#181]
Distribution: Archlinux

Steps to reproduce:
* Goto https://mozilla.github.io/webrtc-landing/gum_test.html
* Start screencast -> Select "Use os ..." -> ... -> Screencast is running
* Stop screencast
* Click again on Start screencast
* No UI element to select the Screencast provider ("Use os ...")

Restarting firefox will reset this circle.

Tested with firefox 96 (arch and flatpak) and xdpw from master.

This issue does not occur with the gnome wayland session.

**Comment by columbarius** [comment]
Using `dbus-monitor "interface='org.freedesktop.portal.ScreenCast'" "interface='org.freedesktop.impl.portal.ScreenCast'" "interface='org.freedesktop.portal.Session'"`:

The logs were generated by trying to start two screencast sessions using the flatpak versions of firefox and chromiums.
Note: chromium will always create to double amount of screencast sessions because of it's preview.

[dbus-ff.log](https://github.com/emersion/xdg-desktop-portal-wlr/files/7917361/dbus-ff.log)
[dbus-chromium.log](https://github.com/emersion/xdg-desktop-portal-wlr/files/7917360/dbus-chromium.log)

**Comment by columbarius** [comment]
Update: Falling back to sway 1.6.x solves this issue

**Comment by codicodi** [comment]
I think this is fixed by https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3436

**Comment by columbarius** [comment]
Yeah, wlroots 0.15.1 was released which fixes this problem. Closing the issue.
