### ISSUE TITLE
Screencast freeze with `pipewire_loop_iterate failed`

### ISSUE THREAD

**Issue by freswa** [emersion/xdg-desktop-portal-wlr#186]
Within 30 minutes of screencast, I get about 1-3 freezes, where my opponents just see a frozen screenshare but on my side the browser doesn't indicate any error. In this case I can find the following output in the journal:
`xdg-desktop-portal-wlr[6972]: 2022/01/27 14:59:52 [ERROR] - pipewire_loop_iterate failed: Unknown error -1`

**Comment by columbarius** [comment]
Can you please try #184. I restructured the loop which should be more robust.

**Comment by freswa** [comment]
Got 30 minutes of screencast without freeze. Will test more in the coming days.

**Comment by danielmorlock** [comment]
Unfortunately I cannot confirm the bug, using xdg-desktop-portal-1.12.1 and the latest master including #184 I got lots of:
```
2022/03/29 19:51:56 [WARN] - wlroots: no current buffer
2022/03/29 19:51:56 [WARN] - pipewire: out of buffers
2022/03/29 19:51:56 [WARN] - wlroots: failed to dequeue buffer
2022/03/29 19:51:56 [WARN] - wlroots: no current buffer
```
Ending in a segfault of my Brave/Chromium browser.

**Comment by danielmorlock** [comment]
I cannot confirm the fix in #184 after starting a screencast, I get lots of the following errors (when running `/usr/libexec/xdg-desktop-portal-wlr -lDEBUG`): 
```
2022/03/29 20:01:03 [WARN] - wlroots: no current buffer
2022/03/29 20:01:03 [WARN] - pipewire: out of buffers
2022/03/29 20:01:03 [WARN] - wlroots: no current buffer
2022/03/29 20:01:03 [WARN] - pipewire: out of buffers
2022/03/29 20:01:03 [WARN] - wlroots: no current buffer
2022/03/29 20:01:03 [INFO] - pipewire: stream state changed to "paused"
2022/03/29 20:01:03 [INFO] - pipewire: node id is 84
2022/03/29 20:01:03 [WARN] - pipewire: no buffer to queue
2022/03/29 20:01:03 [WARN] - pipewire: out of buffers
2022/03/29 20:01:03 [WARN] - wlroots: no current buffer
```
After a while Brave/Chromium are ending up in a segfault. I'm using `xdg-desktop-portal-1.12.1` and `pipewire 0.3.48`.

**Comment by danielmorlock** [comment]
Also tested `xdg-desktop-portal-1.14.1` without success.

**Comment by columbarius** [comment]
> 2022/03/29 20:01:03 [INFO] - pipewire: stream state changed to "paused"
> 2022/03/29 20:01:03 [INFO] - pipewire: node id is 84
> 2022/03/29 20:01:03 [WARN] - pipewire: no buffer to queue
> 2022/03/29 20:01:03 [WARN] - pipewire: out of buffers

Can you please share the whole log with `-lTRACE`? I'd like to see that, because out of buffer shouldn't happen anymore if the stream was paused.

**Comment by columbarius** [comment]
@freswa Do you have still freezes or can we close this issue?

**Comment by freswa** [comment]
Haven't had long screenshare sessions since, but I had no problems either. Closing this for now.
