### ISSUE TITLE
Blank/No Screen Share with Test-Script

### ISSUE THREAD

**Issue by L3MON4D3** [emersion/xdg-desktop-portal-wlr#187]
Hi, I'm unable to share my screen with both the python test-script and the [webrtc test page (with firefox)](https://mozilla.github.io/webrtc-landing/gum_test.html)

I'm using:
* pipewire 0.3.44
* wireplumber 0.4.7
* xdpw c34d098 (current master)
* sway 1.7
* wlroots 0.15.0

The script produces the following output:
```bash
[~]$ python xdp.py 
session /org/freedesktop/portal/desktop/session/1_27/u1 created
sources selected
streams:
stream 4294967295
```

I'm unsure what exactly causes this, opening the issue in xdpw because the symptoms seem similar to #168, which was resolved here.

logs:
[pw.log](https://github.com/emersion/xdg-desktop-portal-wlr/files/7985633/pw.log)
[wp.log](https://github.com/emersion/xdg-desktop-portal-wlr/files/7985635/wp.log)
[xdpw.log](https://github.com/emersion/xdg-desktop-portal-wlr/files/7985637/xdpw.log)

I've also gone through the [troubleshooting-checklist](https://github.com/emersion/xdg-desktop-portal-wlr/wiki/%22It-doesn't-work%22-Troubleshooting-Checklist), but all of these are set up properly on my end.

**Comment by L3MON4D3** [comment]
Yep: 
[xdpw2.log](https://github.com/emersion/xdg-desktop-portal-wlr/files/7987368/xdpw2.log)

Not sure if it's relevant, but I have to SIGQUIT to stop the script.

**Comment by columbarius** [comment]
Failed to reproduce your issue with the same pipewire version.
The returned stream id `4294967295` is far to high. 
What confuses me is that xdpw should log the returned stream value which doesn't happen. 
Could you please add an `abort();` before every `return ret` or `return -1` from https://github.com/emersion/xdg-desktop-portal-wlr/blob/master/src/screencast/screencast.c#L425 on and try to run it again?

For completeness what distro are you using?

**Comment by L3MON4D3** [comment]
Okay, big misconfiguration on my part: I was using a leftover, I assume, version of `xdg-desktop-portal-wlr` and its' corresponding systemd-service, both located in `usr/local/` and therefore shadowing the newer, working!!, versions from the AUR-package :facepalm:

Thank you for your help and putting me on the correct path (eg. building from source and running the result directly), apologies for any time wasted :/
