### ISSUE TITLE
Exit when the screen has not been shared for 10 minutes

### ISSUE THREAD

**Issue by cljoly** [emersion/xdg-desktop-portal-wlr#188]
How would you feel about having `xdg-desktop-portal-wlr` exit when it has not been sharing the screen for a while, say 10 minutes?

I think this would bring the following benefits:
* resource conservation: free some (small) amount of resources, as on my machine, an idle `xdg-desktop-portal-wlr` process uses around 3MB of RAM
* security: I currently have an indicator in my swaybar, to show that the daemon is running and that my screen might be being shared. If the daemon exited when it’s not used, the indicator would more reliable indicate that something unexpected is going on.

**Comment by emersion** [comment]
It's called exit-on-idle. It needs a lot of caution when implementing it, to avoid race conditions. See https://lists.freedesktop.org/archives/systemd-devel/2017-May/038890.html.

> security: I currently have an indicator in my swaybar, to show that the daemon is running and that my screen might be being shared. If the daemon exited when it’s not used, the indicator would more reliable indicate that something unexpected is going on.

That's not a good way to do this. Instead, monitoring the PipeWire IPC should be a lot more robust.

**Comment by cljoly** [comment]
Ok, thanks for your answer.
