### ISSUE TITLE
Chooser menu presented 2 times when screen sharing

### ISSUE THREAD

**Issue by paolomainardi** [emersion/xdg-desktop-portal-wlr#197]
Testing here: https://mozilla.github.io/webrtc-landing/gum_test.html (it happens on any webrtc based app).

Just a simple standard `xdg-desktop-portal-wlr` conf:

```
> cat .config/xdg-desktop-portal-wlr/sway
[screencast]
chooser_type=dmenu
chooser_cmd=wofi --show=dmenu
```

This is the sequence i see all the times:

1)  ![image](https://user-images.githubusercontent.com/8747/162578715-df8a6267-0a37-439e-b843-5d44d64fcb41.png)

2) ![image](https://user-images.githubusercontent.com/8747/162578724-00fa8ebb-a8ad-41bc-848e-a169ac9aee2d.png)

3) ![image](https://user-images.githubusercontent.com/8747/162578729-b14b137e-17ab-4ba2-909c-aaf042771a3c.png)

4) ![image](https://user-images.githubusercontent.com/8747/162578735-11336a32-2e29-478c-aa9b-34cdb9ed8188.png)

As you can see point 1 and 3 both run the chooser_cmd the let me select the screen, which is already selected.

Am i seeing something wrong here or it is the current implementation to behave like this ?

Thanks!

**Comment by columbarius** [comment]
Chromium insists on using it's own chooser, while it can't transfer the already opened stream from it's chooser to the actual screencast, so it queries two times (once for its chooser and once for the screencast). If you are funny you can select another stream the second time. This can be solved by #170 if chromium also implements (has implemented, don't know the current state) the client side of the mechanism.
