### ISSUE TITLE
tag/release request

### ISSUE THREAD

**Issue by prometheanfire** [emersion/xdg-desktop-portal-wlr#204]
https://bugs.gentoo.org/832181#c4 confirmed that there was some fix to make it work better with gnome, unknown which commit though.  We could make a pre-release ebuild but would prefer not to if possible.

Thanks

**Comment by columbarius** [comment]
We plan to create a new release this month. Support for hardware buffers was recently merged and I'd like to give people some time to find issues.

**Comment by emersion** [comment]
https://github.com/emersion/xdg-desktop-portal-wlr/releases/tag/v0.6.0
