### ISSUE TITLE
 Allow sharing of multiple different screens

### ISSUE THREAD

**Issue by kilimnik** [emersion/xdg-desktop-portal-wlr#220]
When trying to do multiple streams, currently the first stream opens with a slurp section, but when trying to initiate another stream, There is no selection, and the same screen gets shared as in the first stream.

The FAQ mentions sharing of multiple outputs and mentions, that the issue #12 has to be resolved first. 

I tested that with Chromium as well as Firefox.

**Comment by kilimnik** [comment]
I am using version 0.5.0 on NixOS.

**Comment by columbarius** [comment]
Please provide a log file with loglevel `TRACE`
