### ISSUE TITLE
Feature: Allow v4l2 streams to be selected 

### ISSUE THREAD

**Issue by wernerb** [emersion/xdg-desktop-portal-wlr#221]
The Share Desktop/Screencast feature is most of the time treated with higher bitrate for Google Meet/Teams etc than the webcam (locked at 720p and low bitrate).
Sometimes you might want to broadcast a video source instead of the desktop, e.g., for meetings/conferences.
Could xdg-desktop-portal-wlr be modified to allow exposing v4l2 devices?

**Comment by columbarius** [comment]
xdg-desktop-portal-wlr could be modified to stream either v4l2 devices or relay your v4l2 device exported via PipeWire, but this is a non-goal for this project.
