### ISSUE TITLE
Horrible quality of screen sharing

### ISSUE THREAD

**Issue by peterwilfride** [emersion/xdg-desktop-portal-wlr#225]
# problem
I need to share my screen. I follow all the steps [here](xdg-desktop-portal-wlr) but all I have is a screen share with a very bad quality. Before I was totaly black.

![1657410501_grim](https://user-images.githubusercontent.com/41086317/178126166-1e8c2714-0c56-4431-a579-252d5d44b9cc.png)

What is going go?

# Info
Distro: Endevouros 
WM: sway 1.7
browser: vivaldi (also test in chromium) 

# environment variables
MOZ_ENABLE_WAYLAND=1
XDG_CURRENT_DESKTOP=sway
XDG_SESSION_DESKTOP=sway
WAYLAND_DISPLAY=wayland-1
XDG_CURRENT_DESKTOP=sway

# packages installed
pipewire
xdg-desktop-portal
xdg-desktop-portal-wlr
libpipewire02

# in vivaldi / chromium
vivaldi://flags/#enable-webrtc-pipewire-capturer 
I ensure this plugin is enable

**Comment by grulja** [comment]
This is a bug in Chromium (WebRTC) which will be fixed in version 105.

Upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1333304

**Comment by columbarius** [comment]
Thanks @grulja 

@peterwilfride I'll close this for now. If you encounter this issue again with chromium 105 and later please add it to #223
