### ISSUE TITLE
screencast: remove force pixel format option

### ISSUE THREAD

**Issue by emersion** [emersion/xdg-desktop-portal-wlr#23]
This is a hack used to make some broken clients work. Clients should be fixed instead.

**Comment by emersion** [comment]
Or maybe we could have a less dangerous flag like `--strip-alpha`.

**Comment by danshick** [comment]
I've been chatting with @jgrulich on #pipewire. He's the original implementer in WebRTC. He was under the impression that BGRx or RGBx would accept alpha channel metadata by default, but we confirmed it does not.

Anyway, he's working on some refactoring (and eventually pipewire 0.3 support) in the WebRTC codebase and will include a fix for these pixel formats being rejected as well as correcting support for framerates other than a variable framerate.

In the meantime though, I agree with you, we can at least modify the flag to be less of a hack.

**Comment by emersion** [comment]
Maybe we can advertise support for both the format with alpha and the format without alpha? This wouldn't require any flag.

**Comment by danshick** [comment]
I thought about doing this in the beginning but I didn't want to introduce any format conversion here, and I wanted to accurately report what wlroots provided as the default. I suppose it's not too far off to offer either A or x if the x literally means "these bits are present, but we ignore them".

**Comment by emersion** [comment]
I agree we don't want to do any format conversion, but yeah stripping alpha doesn't require any format conversion. We already need to maintain a format table so I don't think it'd be a big deal.

**Comment by danshick** [comment]
I don't even think we need to change any bytes, because that last byte of color information is just ignored. Is there any spec that says those bytes must be zeroed for proper format compliance?

**Comment by emersion** [comment]
No, the X means "it can be anything". We already do something similar in wlroots' DRM backend: https://github.com/swaywm/wlroots/blob/904c37845dec60fc5ee91d11b5e6c75656651b33/backend/drm/drm.c#L337
