### ISSUE TITLE
Implement Screenshot portal v2

### ISSUE THREAD

**Issue by GeorgesStavracas** [emersion/xdg-desktop-portal-wlr#230]
The Screenshot impl D-Bus API now has a "version" property, I guess it'll be good if you implement that property with version = 2.

**Comment by columbarius** [comment]
Thanks for this information. Do I have to wait until the next xdg-desktop-portal release? Adding the property now the same way as for screencast creates a segfault.

**Comment by columbarius** [comment]
Nope, sry. I'm just bad with dbus stuff.
