### ISSUE TITLE
i can't get screen sharing to work tried everything on the faq

### ISSUE THREAD

**Issue by zooki2006** [emersion/xdg-desktop-portal-wlr#232]
all services are running ( pipewire, pipewire media session,  xdg desktop portal and xdg desktop portal wlr)

systemctl status --user xdg-desktop-portal.service
just gives me

Aug 25 18:40:08 zukiarch xdg-desktop-por[22986]: Failed to close session implementation: Timeout was reached
Aug 25 18:42:50 zukiarch xdg-desktop-por[22986]: A backend call failed: Message recipient disconnected from message bus without replying

im using xdg-desktop-portal-wlr
Version         : 0.6.0-1

.config/xdg-desktop-portal-wlr/config contents is 

[screencast]                                                                                          
output_name=DP-1                                                                                      
max_fps=60                                                                                            
chooser_type=none

i have tried everything i can find on fixing screensharing on wayland with xdp to no avail

WM: sway
GPU: NVIDIA GeForce RTX 3060 Ti

**Comment by zooki2006** [comment]
forgot to add that using pure archlinux

**Comment by columbarius** [comment]
Please post the output of following programs started in this order:
* `/usr/lib/xdg-desktop-portal -v`
* `/usr/lib/xdg-desktop-portal-wlr -r -l DEBUG`

**Comment by zooki2006** [comment]
zuki ~ > /usr/lib/xdg-desktop-portal -v
XDP: load portals from /usr/share/xdg-desktop-portal/portals
XDP: loading /usr/share/xdg-desktop-portal/portals/wlr.portal
XDP: portal implementation for wlroots, sway, Wayfire, river, phosh
XDP: portal implementation supports org.freedesktop.impl.portal.Screenshot
XDP: portal implementation supports org.freedesktop.impl.portal.ScreenCast
XDP: providing portal org.freedesktop.portal.MemoryMonitor
XDP: providing portal org.freedesktop.portal.PowerProfileMonitor
XDP: providing portal org.freedesktop.portal.NetworkMonitor
XDP: providing portal org.freedesktop.portal.ProxyResolver
XDP: providing portal org.freedesktop.portal.Trash
XDP: providing portal org.freedesktop.portal.GameMode
XDP: providing portal org.freedesktop.portal.Realtime

(/usr/lib/xdg-desktop-portal:13590): xdg-desktop-portal-WARNING **: 10:52:47.965: No skeleton to export
XDP: Using wlr.portal for org.freedesktop.impl.portal.Screenshot in sway
XDP: Using wlr.portal for org.freedesktop.impl.portal.ScreenCast in sway
XDP: providing portal org.freedesktop.portal.ScreenCast






zuki ~ > /usr/lib/xdg-desktop-portal-wlr -r -l DEBUG
2022/08/29 10:52:56 [DEBUG] - config: outputname:  DP-1
2022/08/29 10:52:56 [DEBUG] - config: max_fps:  60.000000
2022/08/29 10:52:56 [DEBUG] - config: exec_before:  (null)
2022/08/29 10:52:56 [DEBUG] - config: exec_after:  (null)
2022/08/29 10:52:56 [DEBUG] - config: chooser_cmd: (null)
2022/08/29 10:52:56 [DEBUG] - config: chooser_type: none
2022/08/29 10:52:56 [DEBUG] - config: force_mod_linear: 0
2022/08/29 10:52:56 [DEBUG] - dbus: connected
2022/08/29 10:52:56 [DEBUG] - wlroots: wl_display connected
2022/08/29 10:52:56 [DEBUG] - pipewire: pw_loop created
2022/08/29 10:52:56 [DEBUG] - pipewire: establishing connection to core
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register wl_shm  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: |-- registered to interface wl_shm (Version 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register wl_drm  (Version: 2)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwp_linux_dmabuf_v1  (Version: 4)
2022/08/29 10:52:56 [DEBUG] - wlroots: |-- registered to interface zwp_linux_dmabuf_v1 (Version 4)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register wl_compositor  (Version: 4)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register wl_subcompositor  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register wl_data_device_manager  (Version: 3)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwlr_gamma_control_manager_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zxdg_output_manager_v1  (Version: 3)
2022/08/29 10:52:56 [DEBUG] - wlroots: |-- registered to interface zxdg_output_manager_v1 (Version 3)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register org_kde_kwin_idle  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwp_idle_inhibit_manager_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwlr_layer_shell_v1  (Version: 4)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register xdg_wm_base  (Version: 2)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwp_tablet_manager_v2  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register org_kde_kwin_server_decoration_manager  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zxdg_decoration_manager_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwp_relative_pointer_manager_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwp_pointer_constraints_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register wp_presentation  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwlr_output_manager_v1  (Version: 2)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwlr_output_power_manager_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwp_input_method_manager_v2  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwp_text_input_manager_v3  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwlr_foreign_toplevel_manager_v1  (Version: 3)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register wp_drm_lease_device_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwlr_export_dmabuf_manager_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwlr_screencopy_manager_v1  (Version: 3)
2022/08/29 10:52:56 [DEBUG] - wlroots: |-- registered to interface zwlr_screencopy_manager_v1 (Version 3)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwlr_data_control_manager_v1  (Version: 2)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwp_primary_selection_device_manager_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register wp_viewporter  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zxdg_exporter_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zxdg_importer_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zxdg_exporter_v2  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zxdg_importer_v2  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register xdg_activation_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwp_virtual_keyboard_manager_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwlr_virtual_pointer_manager_v1  (Version: 2)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwlr_input_inhibit_manager_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwp_keyboard_shortcuts_inhibit_manager_v1  (Version: 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register wl_seat  (Version: 7)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register zwp_pointer_gestures_v1  (Version: 3)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register wl_output  (Version: 4)
2022/08/29 10:52:56 [DEBUG] - wlroots: |-- registered to interface wl_output (Version 1)
2022/08/29 10:52:56 [DEBUG] - wlroots: interface to register wl_output  (Version: 4)
2022/08/29 10:52:56 [DEBUG] - wlroots: |-- registered to interface wl_output (Version 1)
2022/08/29 10:52:56 [DEBUG] - wayland: registry listeners run
2022/08/29 10:52:56 [DEBUG] - wlroots: linux_dmabuf_feedback_handle_main_device called
2022/08/29 10:52:56 [INFO] - xdpw: Using render node /dev/dri/renderD128
2022/08/29 10:52:56 [DEBUG] - wlroots: linux_dmabuf_feedback_format_table called
2022/08/29 10:52:56 [DEBUG] - wlroots: linux_dmabuf_feedback_tranche_target_devices called
2022/08/29 10:52:56 [DEBUG] - wlroots: linux_dmabuf_feedback_tranche_flags called
2022/08/29 10:52:56 [DEBUG] - wlroots: linux_dmabuf_feedback_tranche_formats called
2022/08/29 10:52:56 [DEBUG] - wlroots: linux_dmabuf_feedback_tranche_done called
2022/08/29 10:52:56 [DEBUG] - wlroots: linux_dmabuf_feedback_handle_done called
2022/08/29 10:52:56 [DEBUG] - wayland: xdg output listeners run
2022/08/29 10:52:59 [INFO] - dbus: create session method invoked
2022/08/29 10:52:59 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_462/webrtc1465179511
2022/08/29 10:52:59 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_462/webrtc_session1174273649
2022/08/29 10:52:59 [INFO] - dbus: app_id: 
2022/08/29 10:52:59 [INFO] - dbus: select sources method invoked
2022/08/29 10:52:59 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_462/webrtc75149625
2022/08/29 10:52:59 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_462/webrtc_session1174273649
2022/08/29 10:52:59 [INFO] - dbus: app_id: 
2022/08/29 10:52:59 [INFO] - dbus: option types:3
2022/08/29 10:52:59 [INFO] - dbus: option multiple: 0
2022/08/29 10:52:59 [DEBUG] - dbus: select sources: found matching session /org/freedesktop/portal/desktop/session/1_462/webrtc_session1174273649
2022/08/29 10:52:59 [INFO] - wlroots: capturable output: Dell Inc. model: DELL S2319H: id: 41 name: HDMI-A-1
2022/08/29 10:52:59 [INFO] - wlroots: capturable output: Acer Technologies model: ED270R: id: 42 name: DP-1
2022/08/29 10:52:59 [INFO] - xdpw: screencast instance 0x556268dca8c0 has 1 references
2022/08/29 10:52:59 [INFO] - xdpw: 1 active screencast instances
2022/08/29 10:52:59 [INFO] - wlroots: output: DP-1
2022/08/29 10:52:59 [INFO] - dbus: start method invoked
2022/08/29 10:52:59 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_462/webrtc1001354825
2022/08/29 10:52:59 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_462/webrtc_session1174273649
2022/08/29 10:52:59 [INFO] - dbus: app_id: 
2022/08/29 10:52:59 [INFO] - dbus: parent_window: 
2022/08/29 10:52:59 [DEBUG] - dbus: start: found matching session /org/freedesktop/portal/desktop/session/1_462/webrtc_session1174273649
2022/08/29 10:52:59 [ERROR] - xdg-desktop-portal-wlr: unsupported wl_shm format 0x34324742
zsh: IOT instruction (core dumped)  /usr/lib/xdg-desktop-portal-wlr -r -l DEBUG
zuki ~ >

**Comment by zooki2006** [comment]
thanks i already using a custom pkgbuild for wlroots so i just add that patch to it thanks

**Comment by zooki2006** [comment]
added patch to pkgbuild and it works perfectly
