### ISSUE TITLE
xdg-desktop-portal-wlr isn't in PATH

### ISSUE THREAD

**Issue by iTrooz** [emersion/xdg-desktop-portal-wlr#237]
In the README (https://github.com/emersion/xdg-desktop-portal-wlr/blob/94c45603b9dcb68c775da74b4f4b8dc141eac126/README.md?plain=1#L49) you tell users to use `xdg-desktop-portal-wlr` directly as if it was on the path, but it is located in libexec/lib

I propose to simply add a notice that this command isn't on the path and that you need to locate it in lib/libexec/something else first

**Comment by m34nbunny** [comment]
Agreed on this, just now migrating to Wayland and trying to screen sharing to work. Still struggling but this added to the list of things I had to go hunt down.

**Comment by columbarius** [comment]
Added a section in https://github.com/emersion/xdg-desktop-portal-wlr/wiki/FAQ#how-do-i-run-xdpw
