### ISSUE TITLE
I just want it to work

### ISSUE THREAD

**Issue by DNDEBUG** [emersion/xdg-desktop-portal-wlr#241]
For the love of God
i just can't take it anymore
i'm going to have a stroke  because of the amount of stress this is causing me
i'm hating wayland

i have installed all this trash
i have read the wiki
i have rad a bunch of posts teaching how to do it
but nothing works

**Comment by DNDEBUG** [comment]
dbus-run-session sway
XDG_CURRENT_DESKTOP=sway
XDG_SESSION_TYPE=wayland
pipewire
libpipewire02
wireplumber
 /usr/lib/xdg-desktop-portal -r & /usr/lib/xdg-desktop-portal-wlr
enable pipewire on chrome
MOZ_ENABLE_WAYLAND=1

none of this trash works
no combination of anything i do works

**Comment by emersion** [comment]
This is not the way you ask for help from volunteers.
