### ISSUE TITLE
[BUG] It doesn't work when sway uses 10 bits color

### ISSUE THREAD

**Issue by Zeioth** [emersion/xdg-desktop-portal-wlr#256]
## Description
xdg-desktop-portal-wlr works correctly when I have this line on my sway config

    output * render_bit_depth 8

But it displays a black screen when

    output * render_bit_depth 10

## More info

* sway:  1:1.8-3
* pipewire: 1:0.3.63-6
* xdg-desktop-portal-wlr: tested on 0.6.0-1 and v0.6.0.r7.ga18bea8-1 (git)

**Comment by Zeioth** [comment]
Tested on OBS 29

**Comment by columbarius** [comment]
OBS requires this patch to support 10bit colours: https://github.com/obsproject/obs-studio/pull/6247.

**Comment by Zeioth** [comment]
Testing this. Blocked by https://github.com/hyprwm/Hyprland/issues/4195

**Comment by Zeioth** [comment]
Ok tested and working. This patch was added to OBS 30:
![screenshot_2023-12-19_21-09-46_394137475](https://github.com/emersion/xdg-desktop-portal-wlr/assets/3357792/55e65a21-6bc7-4564-89c3-1b9d61871050)
Thank you so much for the awesome work columbarius.
