### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by Mxbonn** [emersion/xdg-desktop-portal-wlr#257]
I would like to use the provided functionality from the screenshot portal V2 which was fixed in #231, which is not yet in a release, hence not yet available in package managers.
See also: https://github.com/flameshot-org/flameshot/issues/2872#issuecomment-1354741019_

**Comment by columbarius** [comment]
screenshot portal v2 is not implemented, but version 1 is and we now announce it correctly. 

I've created a milestone to collect things required for a new release.

**Comment by mvdan** [comment]
For the sake of linking issues together: a new release might fix or improve support with newer browsers, e.g. https://github.com/emersion/xdg-desktop-portal-wlr/issues/266.

**Comment by clawoflight** [comment]
Hi @columbarius, with current pipewire and apps (chrome, flameshot, ...) this simply does not work anymore. It appears that the required changes are already there - if so, could you please distribute a new release so we can at least get our functionality back? Then you can take your time to finish the new features you are working on :)

**Comment by columbarius** [comment]
Looked through the history and current master looks fine, so we will do a release soon.

**Comment by mvdan** [comment]
For those who haven't noticed yet, a release [happened yesterday](https://github.com/emersion/xdg-desktop-portal-wlr/releases/tag/v0.7.0). I suspect that distros like Arch will pick it up soon. I think this issue and others like https://github.com/emersion/xdg-desktop-portal-wlr/issues/266 can now be closed.

**Comment by columbarius** [comment]
Release happened, so I'll close this.
