### ISSUE TITLE
Stopped working with Firefox since version 110.0

### ISSUE THREAD

**Issue by dcompoze** [emersion/xdg-desktop-portal-wlr#262]
This might be a Firefox issue but I'm not exactly sure.

Sway version: `1.8.1`

Pipewire version: `0.3.66`

Wireplumber version: `0.4.13`

xdg-desktop-portal version: `1.16.0`

xdg-desktop-portal-wlr version: `0.6.0`

Firefox peer connection enabled: yes

Last Firefox version that worked: `109.*`

First Firefox version that stopped working: `110.0`

Using this demo application: https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing

Normally it would show a browser prompt to select the screen to share when clicked.

Now it produces the following error:

![selection-1677848492](https://user-images.githubusercontent.com/76269710/222728506-0373dd3b-7698-4d33-abec-963ef19d8d83.png)

I tried launching Firefox with default settings/profile but it produced the same error.

It still works correctly on Chromium and older versions of Firefox which would suggest that the portal is configured correctly.

There are no exceptional logs for the xdg-desktop-portal and xdg-desktop-portal-wlr services.

**Comment by columbarius** [comment]
Are you using the flatpak version of firefox? For me the flatpak produced the same error, while the version from the arch repository still worked.

**Comment by dcompoze** [comment]
I'm also using the one from the Arch Linux repo, both v100.0 and v100.0.1 show the same error. If I install v109.0.1 from the pacman cache it works fine.

**Comment by shaohme** [comment]
I've got the same issue. 

Using Devuan with latest testing packages, including Firefox 110.0.1

**Comment by smlx** [comment]
I'm on the flatpak version of Firefox 110 and it's working here.

**Comment by 3lpsy** [comment]
@dcompoze Do you have xwayland installed?

https://github.com/emersion/xdg-desktop-portal-wlr/issues/261

**Comment by hvhaugwitz** [comment]
FWIW I experienced a similar issue with Firefox 110; with Firefox 111 screen sharing is working again.

**Comment by dcompoze** [comment]
@3lpsy I don't have xwayland server installed and also have configured sway to `xwayland disable` in sway/config.

**Comment by dcompoze** [comment]
It seems to work correctly since version 111.0 so I'm going to close this issue.
