### ISSUE TITLE
UseIn= superseded by per-DE portal configurations

### ISSUE THREAD

**Issue by kennylevinsen** [emersion/xdg-desktop-portal-wlr#268]
As of https://github.com/flatpak/xdg-desktop-portal/commit/939f0b0fcec6a42c1acdc397986547e9805359ff, UseIn= has been superseded by a portal configuration file.

This file is means to exist per "Desktop environment" (i.e., the `XDG_CURRENT_DESKTOP` value), and can specify providers per portal, as well as a default. This allows us to circumvent the major nuisance of the GNOME portal being used as fallback.

Do we want to carry an example here, have compositors carry their own, or let package managers define one suitable for their distro and dependencies?

**Comment by columbarius** [comment]
I've tested the new configuration file and it still takes arround 20-30 seconds for gtk applications to start, but after that they are no longer unresponsive. 

I can upload my configuration file as an example, but I'd suggest compositors shipping their own configuration file, which distro maintainers can adapt to their choice of components.

I'll ask xdg-desktop-portal for a new release.
