### ISSUE TITLE
Unsupported wl_shm format 0x34324742

### ISSUE THREAD

**Issue by avargas05** [emersion/xdg-desktop-portal-wlr#299]
I'm attempting to use OBS Studio to capture the screen. It fails to start the screencast.

I've captured the log here: https://obsproject.com/logs/4rg2qIRW57QWLSRJ

The key part is the following followed by a systemd coredump:
```log
Mar 23 17:21:53 arch sway[16394]: info: [pipewire] Screencast session created
Mar 23 17:21:56 arch sway[16394]: info: [pipewire] Asking for desktop
Mar 23 17:21:56 arch xdg-desktop-portal-wlr[15741]: 2024/03/23 17:21:56 [ERROR] - xdg-desktop-portal-wlr: unsupported wl_shm format 0x34324742
```
While investigating I found the same thing happens when trying to use the screen capture tool from Mozilla's WebRTC landing page: https://mozilla.github.io/webrtc-landing/gum_test.html

**Comment by emersion** [comment]
This is BGR888, added in https://github.com/emersion/xdg-desktop-portal-wlr/commit/84a9cf40fb6e5b2900c7d245a1ac8acad828a88f
