### ISSUE TITLE
screencast: concurrent sessions with different pixel formats aren't differentiated

### ISSUE THREAD

**Issue by danshick** [emersion/xdg-desktop-portal-wlr#34]
If you attempt to start two sessions with the same cursor mode and output, but where the clients require two different pixel formats, the second session will not negotiate as it attempts to reuse the existing incompatible session.

**Comment by danshick** [comment]
This will be tough to fix, because we assign a session to a cast instance well before the pipewire negotiation begins. Even if we retroactively add that information to the cast instance struct, there'd be no way in the early d-bus session to know whether or not the client will be compatible.

**Comment by progandy** [comment]
I don't really know pipewire configuration, but might it be possible to set up an intermediary source that can connect to another existing source depending on the pixel format it negotiates with the sink?

**Comment by danshick** [comment]
It's probably possible to do this, but we are already pretty far into creating the source by the time we find out about the supported format [here](https://github.com/emersion/xdg-desktop-portal-wlr/blob/f5bfe9fe12ed2d32f727e10a66229f2a7e377bf9/src/screencast/pipewire_screencast.c#L114). Currently, we do nothing with this value, because we send the alpha data whether it is wanted or not, but once the format is chosen, new sinks that don't support it will fail to connect. I'll have to revisit the state machine for this whole setup process to determine how much refactoring is required if we want to take this approach.

I'm kind of hoping this goes away when WebRTC adds support for alpha channel data (it's been discussed with one of the maintainers, they thought that BGRx was inclusive of BGRA, which it isn't, and this is seen as a bug).

**Comment by danshick** [comment]
This problem still _kind of_ exists in the sense that we can't make a determination between two sessions that have differing metadata that is not captured by the xdg portal interface, but exists as a pipewire detail, but it is not currently a problem due to #33. We can close this for now, but it may reappear in the future (most likely as a result of dmabuf or memfd support).
