### ISSUE TITLE
Screencast not working with Fedora Firefox build

### ISSUE THREAD

**Issue by husam212** [emersion/xdg-desktop-portal-wlr#39]
I'm using `fedora-firefox-wayland-bin` and `xdg-desktop-portal-wlr` from AUR, I'm setting XDG_SESSION_TYPE=wayland early in the display manager, I'm getting the following errors:
```
Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list
A backend call failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.impl.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
Failed to close session implementation: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.impl.portal.Session” on object at path /org/freedesktop/portal/desktop/session/1_25/webrtc_session464923418
```

**Comment by danshick** [comment]
This looks like xdpw is not starting correctly. Basically, xdg-desktop-portal is not finding xdg-desktop-portal-wlr. Could easily be that the wlr.portal file is missing or in the wrong place. Confirming that it is present would help. You could run `pacman -Ql xdg-desktop-portal-wlr` and include those results in a paste.

Can you also detail what steps you've taken (if any) after installing xdpw? Are you attempting to start it manually?

**Comment by husam212** [comment]
Here's the output for `pacman -Ql xdg-desktop-portal-wlr`:
```
xdg-desktop-portal-wlr /usr/
xdg-desktop-portal-wlr /usr/lib/
xdg-desktop-portal-wlr /usr/lib/systemd/
xdg-desktop-portal-wlr /usr/lib/systemd/user/
xdg-desktop-portal-wlr /usr/lib/systemd/user/xdg-desktop-portal-wlr.service
xdg-desktop-portal-wlr /usr/lib/xdg-desktop-portal-wlr
xdg-desktop-portal-wlr /usr/share/
xdg-desktop-portal-wlr /usr/share/dbus-1/
xdg-desktop-portal-wlr /usr/share/dbus-1/services/
xdg-desktop-portal-wlr /usr/share/dbus-1/services/org.freedesktop.impl.portal.desktop.wlr.service
xdg-desktop-portal-wlr /usr/share/xdg-desktop-portal/
xdg-desktop-portal-wlr /usr/share/xdg-desktop-portal/portals/
xdg-desktop-portal-wlr /usr/share/xdg-desktop-portal/portals/wlr.portal
```

I'm not running anything manually, systemd shoud handle them, right? I just installed the packages and set `XDG_SESSION_TYPE` and `XDG_CURRENT_DESKTOP` environment variables, then rebooted to make sure systemd picks up everything.

**Comment by danshick** [comment]
Yes, everything should start automatically. Looks like the portal file installed to the correct place IIRC. You're setting session type to "wayland" and current desktop to "sway", right?

If all of those are being done correctly, I'd need you to start both xdp and xdpw manually (as explained in the wiki). Make sure you kill any active instances of both first. For xdpw, use the -l flag with the DEBUG option. For xdp, the --help flag should tell you how to set logging for that. If you could share those, that would be helpful.

I'd be looking out for any errors related to d-bus.

**Comment by husam212** [comment]
Running it manually works, the problem is setting environment variables, I was setting them in the display manager (I use [ly](https://github.com/cylgom/ly)), systemd wasn't picking them up.

**Comment by danshick** [comment]
Glad you got it working.
