### ISSUE TITLE
Few implementation questions

### ISSUE THREAD

**Issue by nostdm** [emersion/xdg-desktop-portal-wlr#4]
I'm not sure if this is a good place to ask but I was wondering a couple of things regarding this project:

Currently when installing `xdg-desktop-portal` on Arch Linux the only provided portal backends that show up are the `kde` and `gtk` implementations. There's an AUR package for `xdg-desktop-portal-liri` but that's also using `qt5`. Ideally I'd like to install `flatpak` + `xdg-desktop-portal` and have it use a non-GUI portal backend together with sway (so that I don't have to install qt5 and gtk dependencies).

I installed this project from source using the recommended `ninja -C build install` but I guess it would have to be an AUR package in order to satisfy the `xdg-desktop-portal` dependency when installing `flatpak` using `pacman`.

Also, I'm not sure if you know this, but could a browser (e.g. Firefox) potentially make use of this portal backend to allow desktop screencasts in applications like Google Meet and other screensharing web apps? Currently these apps don't seem to work in sway. Thanks.

**Comment by emersion** [comment]
>have it use a non-GUI portal backend together with sway (so that I don't have to install qt5 and gtk dependencies)

This isn't what xdg-desktop-portal-wlr provides.

>but could a browser (e.g. Firefox) potentially make use of this portal backend to allow desktop screencasts in applications like Google Meet and other screensharing web apps?

This is what xdg-desktop-portal-wlr is all about.

**Comment by wiktor-k** [comment]
> This is what xdg-desktop-portal-wlr is all about.

:thinking: I just did a quick research including installing portal-wlr and running it (as well as running some random commands from blogposts) and didn't get it to work.

Is this work-in-progress or does screensharing of wayland apps already work in some way?

**Comment by emersion** [comment]
This project isn't ready for end-users yet, sorry.

**Comment by wiktor-k** [comment]
Got it, thanks for the info @emersion! (By the way huge thanks for your work on all sway-related projects!)
