### ISSUE TITLE
Implement org.freedesktop.portal.OpenURI

### ISSUE THREAD

**Issue by ilyazzz** [emersion/xdg-desktop-portal-wlr#42]
It is used by flatpak applications to open links.

When running xdg-desktop-portal-wlr and trying to open a link(in discord for example), `dbus-monitor` shows:
`string "No such interface “org.freedesktop.portal.OpenURI” on object at path /org/freedesktop/portal/desktop"`
With xdg-desktop-portal-gtk, the link opens.

Running sway 1.5 and latest version of xdg-desktop-portal-wlr

**Comment by emersion** [comment]
I don't think wlroots has anything to do with opening links. I suggest you use the GTK portal to provide this portal impl.

**Comment by ilyazzz** [comment]
Is it possible to run two portals simultaneously? Otherwise you would have to switch between portals to either open links or use screen capture.

**Comment by emersion** [comment]
Yes, it's possible. Just installing the GTK portal should be enough. The wlroots portal only claims to support screencapture and screenshots, so Flatpak wil automatically select another portal impl (if any) for the rest.

**Comment by sentriz** [comment]
on my arch based system it seems I can't have `xdg-desktop-portal-gtk` and `xdg-desktop-portal-wlr` installed at the same time. if have just xdpw installed, casting my entire desktop from chrome works great. but if `xdg-desktop-portal-gtk` is installed too, I get this when casting:

```
Jul 31 09:33:38 manjaro xdg-desktop-por[15577]: Failed to close session implementation: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.impl.portal.Session” on object at path /org/freedesktop/portal/desktop/session/1_54/webrtc_session568462190
Jul 31 17:44:14 manjaro xdg-desktop-por[15577]: A backend call failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.impl.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
Jul 31 17:44:14 manjaro xdg-desktop-por[15577]: Failed to close session implementation: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.impl.portal.Session” on object at path /org/freedesktop/portal/desktop/session/1_273/webrtc_session701964990
Jul 31 17:44:14 manjaro xdg-desktop-por[15577]: A backend call failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.impl.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
Jul 31 17:44:14 manjaro xdg-desktop-por[15577]: Failed to close session implementation: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.impl.portal.Session” on object at path /org/freedesktop/portal/desktop/session/1_273/webrtc_session786092191
```

**Comment by danshick** [comment]
Not sure why that's the case for you. The "conflicts" field for xdg-desktop-portal-gtk and xdg-desktop-portal-wlr are both unset. I'm guessing some kind of bad configuration. Fallback code is [here](https://github.com/flatpak/xdg-desktop-portal/blob/dbbe2180384154c642f837cc50a1ff0b1b5a6a34/src/portal-impl.c#L208), which should clearly allow for one portal to fall back to another. You can see evidence of this in the logs if you start xdg-desktop-portal with the -v flag.

Maybe you don't have `XDG_CURRENT_DESKTOP=sway` set?

**Comment by sentriz** [comment]
ah i see. I have `XDG_CURRENT_DESKTOP=sway` but it's set and exported by my login shell before sway is started. maybe the `xdg-desktop-portal.service` can't see that variable

**Comment by sentriz** [comment]
ah `systemctl --user import-environment` seems to have fixed it :D 

do you think it would be crazy do that in something like a "start sway" script? 
https://github.com/sentriz/dotfiles/blob/master/conf_extra/bin/start-sway

**Comment by danshick** [comment]
No, in fact, I would recommend it. Glad you got it working!

@ilyazzz does this seem like the same issue you're having?

**Comment by sentriz** [comment]
works very well. thanks for the help :)

**Comment by ilyazzz** [comment]
@danshick yes! Running `systemctl --user import-environment` before xdg-desktop-portal starts does fix the issue. Both screenshare and links work now.
 I'm also not having the package conflict @sentriz described, maybe manjaro provides own versions of the portal packages?

I initially assumed different portals are implementations of the same spec so I wasn't expecting the two to be working together. Glad this is resolved :D

**Comment by p00f** [comment]
@sentriz so to clarify, you have installed both `xdg-desktop-portal-wlr` and `xdg-desktop-portal-gtk` and run `systemctl --user import-environment` in your start-sway script, after exporting `XDG_CURRENT_DESKTOP=sway` and before the `exec sway` ?

**Comment by sentriz** [comment]
> @sentriz so to clarify, you have installed both `xdg-desktop-portal-wlr` and `xdg-desktop-portal-gtk` and run `systemctl --user import-environment` in your start-sway script, after exporting `XDG_CURRENT_DESKTOP=sway` and before the `exec sway` ?

i've changed things around since then, but yeah both portals are running

![image](https://user-images.githubusercontent.com/6832539/107372883-d0e64280-6add-11eb-8501-6a5062c44464.png)


- the first thing that happens is my login shell exports `XDG_CURRENT_DESKTOP` [[here]](https://github.com/sentriz/dotfiles/blob/7c82f138966d07a2cd401591a0df8ba9b168d0dc/conf_common/.config/fish/config.base.manjaro.fish#L13)
- then sway is started [[here]](https://github.com/sentriz/dotfiles/blob/7c82f138966d07a2cd401591a0df8ba9b168d0dc/conf_common/.config/fish/config.login.manjaro.fish)
- then sway import the envs at the end of the config [[here]](https://github.com/sentriz/dotfiles/blob/7c82f138966d07a2cd401591a0df8ba9b168d0dc/conf_extra/.config/sway/config#L406-L408)

no idea if this is good practice but works well for me

**Comment by trinitronx** [comment]
@sentriz Does this still work in 2023?  I'm not seeing any provided portal for "`org.freedesktop.impl.portal.OpenURI`" in the current version of `xdg-desktop-portal-gtk` package:

```console
$ grep Interfaces /usr/share/xdg-desktop-portal/portals/gtk.portal  | cut -d= -f2  | tr ';' '\n' 
org.freedesktop.impl.portal.FileChooser
org.freedesktop.impl.portal.AppChooser
org.freedesktop.impl.portal.Print
org.freedesktop.impl.portal.Notification
org.freedesktop.impl.portal.Inhibit
org.freedesktop.impl.portal.Access
org.freedesktop.impl.portal.Account
org.freedesktop.impl.portal.Email
org.freedesktop.impl.portal.DynamicLauncher
org.freedesktop.impl.portal.Lockdown
org.freedesktop.impl.portal.Settings
```

**Comment by sentriz** [comment]
@trinitronx I don't see it either, but according to DoorKnocker it's working for me. not sure which portal is implementing it though

however as of recently, you need to [explicitly define which portal has which responsibility](https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals.conf.rst.in) 

so try create a `$XDG_CONFIG_HOME/xdg-desktop-portal/sway-portals.conf`
with

```
[preferred]
default=wlr;gtk
```

then restart all portals

**Comment by trinitronx** [comment]
@sentriz Thanks!  It looks like I was missing that config file after all. :tada:

Seems that there was no default for sway (e.g. `/usr/share/xdg-desktop-portal/sway-portals.conf`)

**Comment by sentriz** [comment]
> Seems that there was no default for sway (e.g. `/usr/share/xdg-desktop-portal/sway-portals.conf`)

nice you got it working :+1: reading [this](https://github.com/emersion/xdg-desktop-portal-wlr/issues/42#issuecomment-1802433964), i think it's up to the users to define their portal configs for themselves
