### ISSUE TITLE
Screenshot: Allow user to take screenshot of region

### ISSUE THREAD

**Issue by tmccombs** [emersion/xdg-desktop-portal-wlr#45]
As the title says. Basically, have a way to select a region for screenshot instead of the entire screen. I'm not sure what the best mechanism for the user to select what kind of screenshot to take is though. Perhaps a simple dialog to choose between region, output, everything or cancel. Or have wait to take the screenshot until the user presses "ENTER" and use different modifiers to select a subset of the screen to capture (ex. Ctrl+click to select an output and Shift+drag to select a region)

**Comment by danshick** [comment]
The latest changes to this portal definition specify an optional "interactive" mode that would either just take the screenshot or allow the user a chance to customize first. I think this should be the approach.

https://github.com/flatpak/xdg-desktop-portal/blob/7f693a7d3918e193488746ccc012588c487363d6/data/org.freedesktop.impl.portal.Screenshot.xml#L49

Also of interest, they added color picker support as well. We could look into implementing this too.
