### ISSUE TITLE
Segfault in iterator when struct member is uninitialized

### ISSUE THREAD

**Issue by danshick** [emersion/xdg-desktop-portal-wlr#52]
Should add some null checking here:
https://github.com/emersion/xdg-desktop-portal-wlr/blob/61db8968f999a23fc7b604fcf7a82a83e7cf268e/src/screencast/wlr_screencast.c#L402

**Comment by ericonr** [comment]
This seems to cause a segfault in https://github.com/emersion/xdg-desktop-portal-wlr/blob/e103e120e20e83acec5b66ce4cd33a0eb86df0b0/src/screencast/wlr_screencast.c#L434 when `xdg-desktop-portal` isn't available/running in the system and one launches x-d-p-w manually.

It prints `2021/02/18 00:43:32 [ERROR] - pipewire: couldn't connect to context` before segfaulting.

**Comment by danshick** [comment]
Yeah, upon another look, while null checking the list is a prudent measure to avoid this segfault, the real bug is here https://github.com/emersion/xdg-desktop-portal-wlr/blob/f0e1de02f44e0be9a065af031c0c9f2457902ab0/src/screencast/screencast.c#L444-L461

We shouldn't be calling finish in the case where we haven't even gotten to the associated init yet.

**Comment by danshick** [comment]
#134 is a duplicate of this bug, but that one has more details even though it is newer. Closing this in favor of it.
