### ISSUE TITLE
Unable to select output in OBS

### ISSUE THREAD

**Issue by skerit** [emersion/xdg-desktop-portal-wlr#57]
When I try to select an output in OBS, OBS outputs this:

    info: OBS XDG initialized (sender name: 1_6790)
    warning: [OBS XDG] Failed to create session, denied or cancelled by user

And this is the output of the `/usr/lib/xdg-desktop-portal -r & /usr/lib/xdg-desktop-portal-wlr` command:

```
** (/usr/lib/xdg-desktop-portal:71318): WARNING **: 23:53:48.900: A backend call failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.impl.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

** (/usr/lib/xdg-desktop-portal:71318): WARNING **: 23:53:48.900: Failed to close session implementation: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.impl.portal.Session” on object at path /org/freedesktop/portal/desktop/session/1_6790/obs13

** (/usr/lib/xdg-desktop-portal:71318): WARNING **: 23:54:02.272: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list
```

Pipewire seems to be up & running... so what am I doing wrong?

**Comment by danshick** [comment]
Sounds like your environment variables are set up wrong. Read this issue thread https://github.com/emersion/xdg-desktop-portal-wlr/issues/56#issuecomment-699582359

The short version is, try putting `exec systemctl --user import-environment' at the bottom of your sway config, log all the way out of your user session and back in.

**Comment by danshick** [comment]
@skerit Did you have a chance to look into your environment variables? Are you still having an issue?

**Comment by skerit** [comment]
I added the environment variables to `~/.config/environment.d/envvars.conf`, but they're still not getting loaded. Even with the `exec systemctl --user import-environment` command added to the sway config.

**Comment by danshick** [comment]
> I added the environment variables to `~/.config/environment.d/envvars.conf`, but they're still not getting loaded. Even with the `exec systemctl --user import-environment` command added to the sway config.

Adding them to the ~/.config/... folder negates the need to use import-environment, but regardless, that should have gotten xdp to load xdpw. Can you share logs with those variables set like you did in your original report?

**Comment by danshick** [comment]
@skerit I'm closing this bug due to inactivity. Please comment and mention me if you are still experiencing this issue.
