### ISSUE TITLE
Deprecate BGRx/RGBx Format Faking

### ISSUE THREAD

**Issue by danshick** [emersion/xdg-desktop-portal-wlr#58]
A commit landed fixing WebRTC handling of BGRA/RGBA pixel formats.

https://webrtc.googlesource.com/src/+/9b87037073f1811bcdae30967167f30b364e6879

Eventually, we can remove the code which reports BGRx/RGBx pixel formats when alpha data is supplied by the compositor.

**Comment by danshick** [comment]
Would fix #34

**Comment by emersion** [comment]
>Would fix #34

Other things might break that again, e.g. DMA-BUF support?

**Comment by danshick** [comment]
> Other things might break that again, e.g. DMA-BUF support?

Depends a lot on how that feature is introduced. If done correctly, and we pass raw DMA-BUFs and modifiers around with no blitting to remove tiling, yes, this would break. Basically, any format parameters not negotiated via d-bus and left to pipewire's negotiation scheme could result in #34 coming back, pixel format just being the first time we ran into that.

If the sort of capability masks discussed on #pipewire are implemented, we may be able to handle this and similar cases in the future.

**Comment by danshick** [comment]
The commit to WebRTC was reverted pending further bugfixes. Follow along here https://webrtc-review.googlesource.com/c/src/+/160649.

**Comment by columbarius** [comment]
> Other things might break that again, e.g. DMA-BUF support?

I do not think so. As discussed, if a client wants to use dmabuf in a way, that would make sense (vaapi, etc.), I guess it probably supports both standards.  Pipewire negotiation and backend choosing is still the main concern regarding dmabuf.

**Comment by danshick** [comment]
This was fixed in #33 a while ago.
