### ISSUE TITLE
Config file format

### ISSUE THREAD

**Issue by columbarius** [emersion/xdg-desktop-portal-wlr#60]
To offer custom options for an outputchooser we need a config file #59 .
To make it easily readable, we should stick to a plaintext, or sway like config.
I could think of an ini like file, where each section could represent a different portal.

Is there something easy adoptable or an often used library?

**Comment by emersion** [comment]
Something like an INI parser is simple enough to bundle with xdpw.

Something I've been wondering about is that we maybe want to allow compositors using xdpw to ship some default config files. This way they could customize xdpw appearance and behaviour without having to tell their users to manually copy-paste a config file. We could for instance look for `$XDG_CONFIG_HOME/xdg-desktop-portal-wlr/config`, then fallback to `/etc/xdg-desktop-portal-wlr/$XDG_CURRENT_DESKTOP`, then fallback to `/etc/xdg-desktop-portal-wlr/config` (or something similar).

**Comment by emersion** [comment]
cc @ammen99: would that be helpful for you?

**Comment by ammen99** [comment]
> cc @ammen99: would that be helpful for you?

Wayfire by default uses all the tools made for Sway (grim/slurp/swayidle/etc) however I am pretty sure some people that are building more full-featured DEs on top of Wayfire would want to provide their own output chooser.

**Comment by columbarius** [comment]
> Something like an INI parser is simple enough to bundle with xdpw.
You mean a self written one, or a dependency like [iniparser](https://github.com/ndevilla/iniparser)?

> Something I've been wondering about is that we maybe want to allow compositors using xdpw to ship some default config files. This way they could customize xdpw appearance and behaviour without having to tell their users to manually copy-paste a config file. We could for instance look for `$XDG_CONFIG_HOME/xdg-desktop-portal-wlr/config`, then fallback to `/etc/xdg-desktop-portal-wlr/$XDG_CURRENT_DESKTOP`, then fallback to `/etc/xdg-desktop-portal-wlr/config` (or something similar).
That would be great! Maybe also `$XDG_CONFIG_HOME/xdg-desktop-portal-wlr/$XDG_CURRENT_DESKTOP`.

**Comment by danshick** [comment]
If we start shipping a config file, which I agree is a good idea, I think it is also time to create some man pages. Right now, the only real documentation is here on the Github Wiki.

**Comment by emersion** [comment]
Opened https://github.com/emersion/xdg-desktop-portal-wlr/issues/67 for the man page.
