### ISSUE TITLE
Screen sharing for Slack using Chrome

### ISSUE THREAD

**Issue by tjaartvdwalt** [emersion/xdg-desktop-portal-wlr#71]
I have recently been able to do screen sharing, when opening Slack in my Chrome browser, instead of the desktop app.
Several months ago, when I tried this, Slack did not support screen sharing through Chrome. 
This enables me to use Sway as my daily driver, while electron is working on adding ozone support.

I wondered if this is worth mentioning in the wiki?
I noticed that the wiki is publicly accessible (I made a test commit). Not sure if this is intentional, but I did not want to add text without the owner's consent.

**Comment by danshick** [comment]
Yeah, this is intentional. The Wiki itself is a git repo underneath, so we could always just roll back bad faith edits.

Feel free to update it. It might be a good idea when discussing Electron apps in the FAQ to mention which have good browser support.

Thanks for contributing!
