### ISSUE TITLE
Request: tag new version

### ISSUE THREAD

**Issue by luispabon** [emersion/xdg-desktop-portal-wlr#78]
Would it be possible to tag a new version please? Ubuntu will be adding first class support for pipewire on the next version, but it won't pick up any of the changes done since 0.1.0 unless a new version is cut soonish.

**Comment by danshick** [comment]
> Would it be possible to tag a new version please? Ubuntu will be adding first class support for pipewire on the next version, but it won't pick up any of the changes done since 0.1.0 unless a new version is cut soonish.

Shouldn't be a problem.

**Comment by emersion** [comment]
I'm thinking of doing a 0.2.0 release with the minor features that have been merged in master quite some time ago, and all of the fixes. Then merge as much of the new stuff as possible (see pending PRs), wait a bit for new bug reports to come in, and release 0.3.0. This would allow us to have a mostly stable 0.2.0, I hope.

@danshick Is that fine with you?

**Comment by danshick** [comment]
> @danshick Is that fine with you?

No issues here. We're still pre 1.0 so I'm not too concerned with the numbering scheme, but we shouldn't wait on config or output selection to do a release.

**Comment by emersion** [comment]
0.2.0 has been released: https://github.com/emersion/xdg-desktop-portal-wlr/releases/tag/v0.2.0
