### ISSUE TITLE
pipewire: couldn't connect to context + segfault (even though pipewire is running)

### ISSUE THREAD

**Issue by simvux** [emersion/xdg-desktop-portal-wlr#79]
I had sway+xdg-desktop-portal-wlr+pipewire running and working for a while on Void Linux (glibc) however it seems to no longer work, and I'm not sure how to troubleshoot from here. 

As far as i know, this error generally appears if pipewire isn't running, and I do get the same error when I turn off pipewire. 
So; it appears that it doesn't detect that pipewire is running even though it is. 

```
 [] : /usr/local/libexec -> echo $XDG_CURRENT_DESKTOP
sway
 [] : /usr/local/libexec -> echo $XDG_SESSION_TYPE
wayland
```

```
 [] : /home/simon -> PIPEWIRE_DEBUG=4 pipewire
[D][pipewire.c:249 pw_load_spa_handle()] load lib:'support/libspa-support' factory-name:'support.log'
[D][pipewire.c:131 open_plugin()] loaded plugin:'/usr/lib64/spa-0.2/support/libspa-support.so'
[D][000000368.690888][logger.c:287 impl_init()] logger 0x55f914cbcd18: initialized
[D][000000368.690893][pipewire.c:249 pw_load_spa_handle()] load lib:'support/libspa-support' factory-name:'support.cpu'
[D][000000368.690898][cpu.c:192 impl_init()] cpu 0x55f914cc0e28: count:12 align:32 flags:0007cbdb
[I][000000368.690901][pipewire.c:458 pw_init()] version 0.3.20
[I][000000368.690907][main.c:80 load_config()] daemon 0x7ffe6e263490: loading config '/etc/pipewire/pipewire.conf'
[D][000000368.690935][main-loop.c:49 loop_new()] main-loop 0x55f914cc1af0: new
[D][000000368.690939][pipewire.c:249 pw_load_spa_handle()] load lib:'support/libspa-support' factory-name:'support.system'
[D][000000368.690941][system.c:348 impl_init()] system 0x55f914cc1b88: initialized
[D][000000368.690944][pipewire.c:249 pw_load_spa_handle()] load lib:'support/libspa-support' factory-name:'support.loop'
[D][000000368.690956][system.c:112 impl_pollfd_create()] system 0x55f914cc1b88: new fd:3
[D][000000368.690960][system.c:218 impl_eventfd_create()] system 0x55f914cc1b88: new fd:4
[D][000000368.690981][system.c:218 impl_eventfd_create()] system 0x55f914cc1b88: new fd:5
[D][000000368.690984][loop.c:815 impl_init()] loop 0x55f914cc1c38: initialized
[D][000000368.690987][system.c:218 impl_eventfd_create()] system 0x55f914cc1b88: new fd:6
[D][000000368.690999][system.c:252 impl_signalfd_create()] system 0x55f914cc1b88: new fd:7
[D][000000368.691011][system.c:252 impl_signalfd_create()] system 0x55f914cc1b88: new fd:8
[D][000000368.691016][context.c:212 pw_context_new()] context 0x55f914cc9f30: new
[D][000000368.691023][data-loop.c:110 loop_new()] data-loop 0x55f914cca9b0: new
[D][000000368.691026][pipewire.c:249 pw_load_spa_handle()] load lib:'support/libspa-support' factory-name:'support.system'
[D][000000368.691029][system.c:348 impl_init()] system 0x55f914ccaa58: initialized
[D][000000368.691032][pipewire.c:249 pw_load_spa_handle()] load lib:'support/libspa-support' factory-name:'support.loop'
[D][000000368.691041][system.c:112 impl_pollfd_create()] system 0x55f914ccaa58: new fd:9
[D][000000368.691045][system.c:218 impl_eventfd_create()] system 0x55f914ccaa58: new fd:10
[D][000000368.691050][system.c:218 impl_eventfd_create()] system 0x55f914ccaa58: new fd:11
[D][000000368.691052][loop.c:815 impl_init()] loop 0x55f914ccab08: initialized
[D][000000368.691055][system.c:218 impl_eventfd_create()] system 0x55f914ccaa58: new fd:12
[D][000000368.691059][mem.c:147 pw_mempool_new()] mempool 0x55f914cd2d20: new
[D][000000368.691063][pipewire.c:249 pw_load_spa_handle()] load lib:'support/libspa-dbus' factory-name:'support.dbus'
[D][000000368.691295][pipewire.c:131 open_plugin()] loaded plugin:'/usr/lib64/spa-0.2/support/libspa-dbus.so'
[D][000000368.691300][dbus.c:403 impl_init()] dbus 0x55f914cd4498: initialized
[D][000000368.691397][impl-core.c:415 pw_context_create_core()] impl-core 0x55f914cd4be0: new pipewire-0
[D][000000368.691402][global.c:106 pw_global_new()] global 0x55f914cd5b10: new PipeWire:Interface:Core 0
[D][000000368.691406][global.c:150 pw_global_register()] global 0x55f914cd5b10: registered 0
[D][000000368.691462][context.c:325 pw_context_new()] context 0x55f914cc9f30: module profile none
[D][000000368.691467][context.c:332 pw_context_new()] context 0x55f914cc9f30: created
[I][000000368.691470][main.c:469 main()] start main loop
[D][000000368.691473][main-loop.c:153 pw_main_loop_run()] main-loop 0x55f914cc1af0: run
[D][000000368.691471][data-loop.c:73 do_loop()] data-loop 0x55f914cca9b0: enter thread
```
```
 [] : /usr/local/libexec -> ./xdg-desktop-portal-wlr --loglevel=DEBUG
2021/01/27 15:21:14 [DEBUG] - dbus: connected
2021/01/27 15:21:14 [DEBUG] - wlroots: wl_display connected
2021/01/27 15:21:14 [DEBUG] - pipewire: pw_loop created
2021/01/27 15:21:14 [DEBUG] - pipewire: establishing connection to core
2021/01/27 15:21:14 [ERROR] - pipewire: couldn't connect to context
zsh: segmentation fault  ./xdg-desktop-portal-wlr --loglevel=DEBUG
```
```
 [] : /usr/libexec -> ./xdg-desktop-portal -r -v
XDP: load portals from /usr/share/xdg-desktop-portal/portals
XDP: providing portal org.freedesktop.portal.MemoryMonitor
XDP: providing portal org.freedesktop.portal.NetworkMonitor
XDP: providing portal org.freedesktop.portal.ProxyResolver
XDP: providing portal org.freedesktop.portal.Trash
XDP: providing portal org.freedesktop.portal.GameMode
XDP: providing portal org.freedesktop.portal.Settings
XDP: org.freedesktop.portal.Desktop acquired
```
^ I think this is also fauly xdg-desktop-portal output? There's no errors but I seem to remember there being more input once it actually connected to pipewire. 

This error appears on both the latest release and after compiling from master branch. 

I start sway using
```
exec dbus-run-session sway
```
and it's using elogind.

**Comment by danshick** [comment]
Not faulty xdp output, just that xdpw is dying before it can report available portals.

On systemd systems, pipewire runs as a socket activated user session. I'd imagine that when using dbus and elogind, pipewire is also meant to be activated by dbus as part of that session, but I've not looked at those configs.

**Comment by simvux** [comment]
```
 [] : /home/simon -> pipewire --version
pipewire
Compiled with libpipewire 0.3.20
Linked with libpipewire 0.3.20
```

**Comment by simvux** [comment]
I'm gonna troubleshoot this a bit on-and-off but should be a good idea to leave the issue up incase this is something hit by all void-users. It being caused by an mainline void update doesn't seem unlikely considering how this was working for me before.

**Comment by danshick** [comment]
Yeah, if you can confirm that a pipewire included example is broken, that will solidify it for me that we aren't the responsible party, but I'll leave this up for now. Thanks.

**Comment by sochotnicky** [comment]
FWIW, I can confirm that screensharing works with pipewire 0.15.0 just fine, but at least since 0.18+ it wasn't working right. In 0.18.0 things at least didn't crash as they do in 0.20. I can try to bisect pipewire to see what commit broke this.

Last time I filed a pipewire bug they were really quick to fix things..

**Comment by danshick** [comment]
> FWIW, I can confirm that screensharing works with pipewire 0.3.15 just fine, but at least since 0.3.18+ it wasn't working right. In 0.3.18 things at least didn't crash as they do in 0.3.20. I can try to bisect pipewire to see what commit broke this.
> 
> Last time I filed a pipewire bug they were really quick to fix things..

Yeah, they're a super helpful community. Sometimes helps to get on #pipewire on freenode as well.

I would still suggest trying to reproduce with an example inatead of xdpw, so that those folks can repeat your experiment. Most of them are Gnome users and cant use xdpw.

**Comment by simvux** [comment]
Running any of the `pw-*` utilities result with `Can't connect: Host is down` so I'm thinking that means we can conclude that this doesn't have to do with xdpw, and instead have all to do with *nothing* being able to connect to pipewire. 

You can close the issue if you want.

**Comment by simvux** [comment]
Actually, I just fixed it. My config /etc/pipewire.conf was using an old format and next to it there was an `pipewire.conf.new-<version>` which i replaced the old one with. Pretty strange that it doesn't overwrite the no longer functioning config by default. 

Screensharing now works again!

**Comment by sochotnicky** [comment]
Yeah, I was wondering why I could not reproduce myself as I was about to bisect this and I can confirm that having an old config lying around will cause this.  In my case (Gentoo) it was pointed out by the config management system after update but I missed it. In 99% cases the apps don't misbehave like this when an old config is lying around. Oh well..
