### ISSUE TITLE
screenshare freeze

### ISSUE THREAD

**Issue by tuxPT** [emersion/xdg-desktop-portal-wlr#81]
I don't know if this problem is from xdg-desktop-portal or from this implementation. But when I share for some time, after some minutes the screenshare freezes(the image does not change, like a photo) with discord, zoom and firefox, the only ones I use for screenshare. I currently workaround this by stopping and reshare again in these programs.

**Comment by danshick** [comment]
Hmmm, I'd be curious to see some logs. Would you feel comfortable running xdp and xdpw manually (explained in the FAQ) with the `-l DEBUG` flag?

**Comment by David96** [comment]
Sounds like #69 (where I still wasn't able to get meaningful WebRTC logs, sorry) to me, except that Zoom afaik doesn't use electron and therefore maybe doesn't use WebRTC which would mean there's another implementation which seems to fail.

Which brings me to a slightly off topic question: how did you manage to get screensharing to work with zoom and discord without using their web clients? Passing the WebRTCPipeWireCapturer feature flag to electron for some reason still doesn't enable screensharing in discord for me.

**Comment by tuxPT** [comment]
https://gitlab.com/jamedjo/gnome-dbus-emulation-wlr

**Comment by tuxPT** [comment]
but it isn't from that because firefox webrtc(jitsi, teamsweb, zoomweb, discordweb) also freezes.
Din't provide any logs beacuaseI haven't share any screen yet, but seems the bug from #69 from the simptoms

**Comment by danshick** [comment]
Yeah, I don't want to muddy the waters on this issue by bringing in clients not built to use xdg-desktop-portal screensharing.

If/when you can share logs, we can take a closer look to see if this resembles the symptoms from #69.

I'd be curious if your setup shares anything in common with others who have this problem that mine does not. I've been screensharing recently for 3+ hours at a time with no issues.

**Comment by junglerobba** [comment]
I am seeing the same problem, and with clients using the portal directly on sway/wlroots master and pipewire 0.3.21 on Arch Linux with a Radeon 5700XT.
On Firefox and OBS with the [PR for Wayland support](https://github.com/obsproject/obs-studio/pull/3338) and [obs-xdg-portal](https://gitlab.gnome.org/feaneron/obs-xdg-portal) the screenshare freezes almost instantly. The Chrome Flatpak seems to be working so far however.

https://gist.github.com/junglerobba/ee2ccc37df050af9eb374b40f451ec73
The screenshares in that log are 1. Chrome Flatpak, 2. Firefox, 3. OBS.
Interestingly enough, the OBS Beta from Flathub, which should use the same patches and portal plugin that I am applying works fine.

(Working fine here means mostly that it didn't freeze instantly, I didn't let it run for multiple hours yet)

**Comment by tuxPT** [comment]
@danshick freeze in aur/fedora-firefox-wayland-bin xdpw logs [xdpw.log](https://github.com/emersion/xdg-desktop-portal-wlr/files/5959737/xdpw.log)

**Comment by danshick** [comment]
@tuxPT @junglerobba @David96 Is it possible that some or all of you are running into #79 or some version of it? Could one or all of you try completely uninstalling pipewire, removing all of its config files, and reinstalling it?

**Comment by junglerobba** [comment]
My pipewire config is identical to the one provided by the Arch package, so I'm not sure if reinstalling will achieve anything except causing a bunch of dependency problems (correct me if I'm wrong).
However I don't know if the problem is really just caused by pipewire, since I also have gnome installed on the same system and with that all the examples I mentioned work just fine.
Unfortunately, I also couldn't get Firefox to produce any logs.

**Comment by danshick** [comment]
No. If your configs are standard, there's no reason to reinstall.

I'm a little stuck to be honest. I can't reproduce this anywhere. Currently running the latest from git master for everything and I can't reproduce this. Tonight, during a three hour stream, I used the pipewire jack dropin to redirect vlc's audio to chromium, and shared a video (with its audio) in MS Teams. So pipewire was handling unmetered screen frames and emulating jackd with no stability issues anywhere.

The only thing I can't test is a GPU other than integrated Intel, but I don't know why that would matter.

**Comment by emersion** [comment]
Maybe try https://github.com/emersion/xdg-desktop-portal-wlr/pull/87?

**Comment by junglerobba** [comment]
Can confirm that #87 fixes the instant freezing.

**Comment by danshick** [comment]
@emersion Good catch! I never would have found this.

**Comment by tuxPT** [comment]
#87 fixes the issue, please merge
