### ISSUE TITLE
Screensharing also transformed if screen transformed (e.g. rotated 180°)

### ISSUE THREAD

**Issue by cshapeshifter** [emersion/xdg-desktop-portal-wlr#83]
I have a Dell XPS 2-in-1 (7390) which can be placed on a table in "tent mode", where the screen is flipped back. This means that the screen content needs to be rotated. In sway, I simply do `output $internal transform 180` and that works well.

However, if I then share my screen (tested in Microsoft Teams in Chromium and Google Hangouts in Firefox), the image I'm sharing is flipped on its head. This is probably not desired. Basically I cannot use screensharing with the laptop it tent mode.

`grim` takes screenshots fine with the expected orientation. Not quite sure where to file this, but I'm guessing the bug is not in firefox, chromium, sway or wlroots. Maybe xdg-desktop-portal or pipewire?

Versions:
```
chromium 88.0.4324.96-2
firefox 85.0-1
libpipewire02 0.2.7-1
linux 5.10.11.arch1-1
pipewire 1:0.3.20-1
sway 1:1.5.1-1
wlroots 0.12.0-1
xdg-desktop-portal-wlr 0.1.0-5
```

**Comment by danshick** [comment]
This is 100% our bug. Grim has code for dealing with transforms that we don't:

https://github.com/emersion/grim/blob/2278f444771f088278dd8c216a18b8f3515b9f88/output-layout.c#L34

**Comment by columbarius** [comment]
If we want to support transforming while screensharing, we probable need #46. 
There are clients, which support changing the dimensions of the screencast like firefox and others, which don't support it, but then the screenshare breaks anyway.

**Comment by emersion** [comment]
This issue is not about changing the output settings while recording. It's about rotating buffers so that they appear with the correct orientation. I don't think it's related to #46.

**Comment by emersion** [comment]
I guess the OP does make it sound like handling output setting changes while recording is desirable. This is much more complicated though, I'd rather do it separately once we handle the basic rotation.

**Comment by cshapeshifter** [comment]
No, I really don't mean making transformations during sharing. By saying "However, if I **then** share my screen", I meant just that. First rotate, then after that try to share -> the shared screen is upside down.

**Comment by danshick** [comment]
Flipping 180° requires no change to pipewire params, even if done abruptly from frame to frame. Rotations by 90° or resizes would require #46 if they occurred mid-stream.

One simple thing we could do now is support detecting orientation on start, and gracefully exiting on output transformations instead of badly crashing or causing undefined behavior.

**Comment by danshick** [comment]
One last note, the way the Gnome devs handled window sharing was by sharing frames that were the full dimension of the screen, only painting the window into the frame where it was positioned on the screen (leaving the rest of the pixels zeroed), and setting the pipewire crop metadata to the location and size of the window. That way, they could handle arbitrary resizes and moves on the fly.

If we took the larger of the two screen dimensions and painted square frames that size, we could handle any rotation on the fly with the crop metadata only by painting the entire screen buffer into that square frame in any arbitrary orientation. The downside is this would involve more memory being copied per frame (albeit empty memory).

**Comment by emersion** [comment]
Suggested a new Pipewire feature here: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/716

But yeah, we can't rely on the other side supporting it.

**Comment by cs** [comment]
Just wanted to point out that wf-recorder has exactly the same issue https://github.com/ammen99/wf-recorder/issues/173.

**Comment by Iss-in** [comment]
hey, happy to see that the upstream pipewire solution is merged, can we see it working properly with pipewire and wlroots master ?

**Comment by columbarius** [comment]
We can close this, since #245 was merged. Now clients have to use this information to display the buffers correctly.
