### ISSUE TITLE
gUM test page shows nothing

### ISSUE THREAD

**Issue by minhduc0711** [emersion/xdg-desktop-portal-wlr#88]
Hello, I have recently updated `xdg-desktop-portal-wlr` to include #87. However I think I might have broken something when updating, and now the gUM test page would show nothing.

When looking at the [xdpw logs](https://gist.github.com/minhduc0711/08ec28786f0130089ee8a14ecd1f3c2c), I noticed that the stream state would get stuck in `paused`:
```
2021/02/12 11:07:24 [INFO] - pipewire: stream state changed to "connecting"
2021/02/12 11:07:24 [INFO] - pipewire: node id is -1
2021/02/12 11:07:24 [INFO] - pipewire: stream state changed to "paused"
2021/02/12 11:07:24 [INFO] - pipewire: node id is 37
```
as opposed to logs from earlier, when it was still working:
```
2020/12/18 11:02:04 [INFO] - pipewire: stream state changed to "connecting"
2020/12/18 11:02:04 [INFO] - pipewire: node id is -1
2020/12/18 11:02:04 [INFO] - pipewire: stream state changed to "paused"
2020/12/18 11:02:04 [INFO] - pipewire: node id is 60
2020/12/18 11:02:04 [INFO] - pipewire: stream state changed to "streaming"
2020/12/18 11:02:04 [INFO] - pipewire: node id is 60
```

When I tried the gstreamer python script, I got this
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/home/minhduc0711/./xdp-screen-cast.py", line 81, in on_start_response
    play_pipewire_stream(node_id)
  File "/home/minhduc0711/./xdp-screen-cast.py", line 68, in play_pipewire_stream
    pipeline = Gst.parse_launch('pipewiresrc fd=%d path=%u ! videoconvert ! xvimagesink'%(fd, node_id))
gi.repository.GLib.GError: gst_parse_error: no element "pipewiresrc" (1)
```

Here are my packages' versions:
```
libpipewire02 0.2.7-1
pipewire 1:0.3.21-1
sway 1:1.5.1-1
wlroots 0.12.0-1
xdg-desktop-portal-wlr-git v0.1.0.r36.g5401e7f-1
```

**Comment by danshick** [comment]
Your python script error indicates you are missing the package `gst-plugin-pipewire`.

As for the meat of your bug report, I'll see if I can reproduce it tomorrow. Testing for that PR exhibited no strange behavior today.

**Comment by danshick** [comment]
Also, cranking up your log levels may be helpful.

**Comment by minhduc0711** [comment]
@danshick thanks, I have increased the log level to `TRACE`. The last part seems to be repeating itself so I pruned it.

**Comment by danshick** [comment]
Gotcha. We may need to add some additional logging to the PR to figure out where it is getting stuck for you.

**Comment by minhduc0711** [comment]
It mysteriously worked again today, so I guess we can close this. I will post here if I encounter it in the future.

**Comment by danshick** [comment]
Thanks for the report. I'll mark as invalid, but please do come back if it stops working again.

**Comment by mattikan** [comment]
Hi, it seems like I'm suffering from this exact same problem. I'm running Manjaro, xdg-desktop-portal 1.8.0-1, xdg-desktop-portal-wlr 0.1.0-5, pipewire 0.3.22.0.g22d56372-1. Here's the relevant snippet from xdg-desktop-portal-wlr logs:

```
➜  ~ /usr/lib/xdg-desktop-portal-wlr BGRx -l DEBUG
2021/02/18 14:22:36 [DEBUG] - dbus: connected
2021/02/18 14:22:36 [DEBUG] - wlroots: wl_display connected
2021/02/18 14:22:36 [DEBUG] - pipewire: pw_loop created
2021/02/18 14:22:36 [DEBUG] - pipewire: establishing connection to core
2021/02/18 14:22:36 [DEBUG] - wayland: registry listeners run
2021/02/18 14:22:36 [DEBUG] - wayland: xdg output listeners run
2021/02/18 14:22:53 [INFO] - dbus: create session method invoked
2021/02/18 14:22:53 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_22/webrtc2138321972
2021/02/18 14:22:53 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_22/webrtc_session158086375
2021/02/18 14:22:53 [INFO] - dbus: app_id:
2021/02/18 14:22:53 [INFO] - dbus: select sources method invoked
2021/02/18 14:22:53 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_22/webrtc1307298904
2021/02/18 14:22:53 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_22/webrtc_session158086375
2021/02/18 14:22:53 [INFO] - dbus: app_id:
2021/02/18 14:22:53 [INFO] - dbus: option types:3
2021/02/18 14:22:53 [INFO] - dbus: option multiple: 0
2021/02/18 14:22:53 [DEBUG] - dbus: select sources: found matching session /org/freedesktop/portal/desktop/session/1_22/webrtc_session158086375
2021/02/18 14:22:53 [INFO] - wlroots: capturable output: Chimei Innolux Corporation model: 0x1409: id: 36 name: eDP-1
2021/02/18 14:22:53 [INFO] - wlroots: capturable output: BenQ Corporation model: BenQ XL2411T: id: 37 name: HDMI-A-2
2021/02/18 14:22:53 [INFO] - xdpw: screencast instance 0x55bdb465eab0 has 1 references
2021/02/18 14:22:53 [INFO] - xdpw: 1 active screencast instances
2021/02/18 14:22:53 [INFO] - wlroots: output: HDMI-A-2
2021/02/18 14:22:53 [INFO] - dbus: start method invoked
2021/02/18 14:22:53 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_22/webrtc1484913544
2021/02/18 14:22:53 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_22/webrtc_session158086375
2021/02/18 14:22:53 [INFO] - dbus: app_id:
2021/02/18 14:22:53 [INFO] - dbus: parent_window:
2021/02/18 14:22:53 [DEBUG] - dbus: start: found matching session /org/freedesktop/portal/desktop/session/1_22/webrtc_session158086375
2021/02/18 14:22:53 [DEBUG] - pipewire: registered event 0x55bdb465fb10
2021/02/18 14:22:53 [INFO] - pipewire: stream state changed to "connecting"
2021/02/18 14:22:53 [INFO] - pipewire: node id is -1
2021/02/18 14:22:53 [INFO] - pipewire: stream state changed to "paused"
2021/02/18 14:22:53 [INFO] - pipewire: node id is 35
```
I've been testing using [the gUM Test Page](https://mozilla.github.io/webrtc-landing/gum_test.html).

I've also tried using Chromium, and with that I get similar results. The stream state gets stuck in paused, and I can't figure out how to continue debugging from here.

**Comment by danshick** [comment]
@mattikan 

It looks like you aren't starting xdpw correctly.

Please try:

```
/usr/lib/xdg-desktop-portal -r & /usr/lib/xdg-desktop-portal-wlr -l DEBUG
```

The BGRx flag is no longer required, and it was not formatted correctly in your command, which might lead to issues. It is also advisable to restart xdp with the `-r` flag before invoking xdpw. Also make sure that you kill any running instances of xdpw before executing this command.

You may also want to try restarting pipewire first as well.

If you try all of that and it isn't resolved, we can reopen the issue and investigate your problem further.

**Comment by mattikan** [comment]
@danshick 

Alright, I killed any running instances of xdp and xdpw, restarted pipewire, and ran that command. I'm still getting identical behaviour. Here's the relevant bit of log, using Firefox 85.0.1, with me closing the tab at :47.

```
➜  ~ /usr/lib/xdg-desktop-portal -r & /usr/lib/xdg-desktop-portal-wlr -l DEBUG
[1] 9211
2021/02/18 18:07:29 [DEBUG] - dbus: connected
2021/02/18 18:07:29 [DEBUG] - wlroots: wl_display connected
2021/02/18 18:07:29 [DEBUG] - pipewire: pw_loop created
2021/02/18 18:07:29 [DEBUG] - pipewire: establishing connection to core
2021/02/18 18:07:29 [DEBUG] - wayland: registry listeners run
2021/02/18 18:07:29 [DEBUG] - wayland: xdg output listeners run
2021/02/18 18:07:37 [INFO] - dbus: create session method invoked
2021/02/18 18:07:37 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_149/webrtc439934716
2021/02/18 18:07:37 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_149/webrtc_session1845944640
2021/02/18 18:07:37 [INFO] - dbus: app_id:
2021/02/18 18:07:37 [INFO] - dbus: select sources method invoked
2021/02/18 18:07:37 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_149/webrtc1338934701
2021/02/18 18:07:37 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_149/webrtc_session1845944640
2021/02/18 18:07:37 [INFO] - dbus: app_id:
2021/02/18 18:07:37 [INFO] - dbus: option types:3
2021/02/18 18:07:37 [INFO] - dbus: option multiple: 0
2021/02/18 18:07:37 [DEBUG] - dbus: select sources: found matching session /org/freedesktop/portal/desktop/session/1_149/webrtc_session1845944640
2021/02/18 18:07:37 [INFO] - wlroots: capturable output: Chimei Innolux Corporation model: 0x1409: id: 36 name: eDP-1
2021/02/18 18:07:37 [INFO] - xdpw: screencast instance 0x557597b5f870 has 1 references
2021/02/18 18:07:37 [INFO] - xdpw: 1 active screencast instances
2021/02/18 18:07:37 [INFO] - wlroots: output: eDP-1
2021/02/18 18:07:37 [INFO] - dbus: start method invoked
2021/02/18 18:07:37 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_149/webrtc520401839
2021/02/18 18:07:37 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_149/webrtc_session1845944640
2021/02/18 18:07:37 [INFO] - dbus: app_id:
2021/02/18 18:07:37 [INFO] - dbus: parent_window:
2021/02/18 18:07:37 [DEBUG] - dbus: start: found matching session /org/freedesktop/portal/desktop/session/1_149/webrtc_session1845944640
2021/02/18 18:07:37 [DEBUG] - pipewire: registered event 0x557597b60900
2021/02/18 18:07:37 [INFO] - pipewire: stream state changed to "connecting"
2021/02/18 18:07:37 [INFO] - pipewire: node id is -1
2021/02/18 18:07:37 [INFO] - pipewire: stream state changed to "paused"
2021/02/18 18:07:37 [INFO] - pipewire: node id is 33
2021/02/18 18:07:47 [INFO] - dbus: session closed
2021/02/18 18:07:47 [DEBUG] - dbus: destroying session 0x557597b5e870
2021/02/18 18:07:47 [DEBUG] - xdpw: screencast instance 0x557597b5f870 now has 0 references
2021/02/18 18:07:47 [DEBUG] - xdpw: destroying cast instance
2021/02/18 18:07:47 [DEBUG] - pipewire: destroying stream
2021/02/18 18:07:47 [INFO] - pipewire: stream state changed to "unconnected"
2021/02/18 18:07:47 [INFO] - pipewire: node id is -1
```

Thanks for taking the time to look at this - this is really new territory for me, and I felt very lost until I found this similar-ish looking issue.

**Comment by danshick** [comment]
This log looks a lot like firefox and xdpw are failing negotiation.

Can you reproduce this with the gstreamer python script (mentioned in the compatibility guide)?

**Comment by mattikan** [comment]
Running the python script results in the following from xdpw's output:

```** (/usr/lib/xdg-desktop-portal:9211): WARNING **: 18:46:59.218: Failed to close session implementation: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.impl.portal.Session” on object at path /org/freedesktop/portal/desktop/session/1_174/u1```

The python script itself only prints `Failed to create session: 2`

**Comment by danshick** [comment]
Can you confirm that you got those errors after running this python script?
https://gitlab.gnome.org/-/snippets/19/raw/master/xdp-screen-cast.py

I don't see why it would complain about the RemoteDesktop interface. Also, xdpw doesn't print logs that look like that. I think those are logs from xdp.

**Comment by mattikan** [comment]
Damnit, sorry - accidentally ran the wrong script. With the correct one, xpdw outputs:

```
2021/02/18 18:59:59 [INFO] - dbus: create session method invoked
2021/02/18 18:59:59 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_187/u1
2021/02/18 18:59:59 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_187/u1
2021/02/18 18:59:59 [INFO] - dbus: app_id:
2021/02/18 19:00:00 [INFO] - dbus: select sources method invoked
2021/02/18 19:00:00 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_187/u2
2021/02/18 19:00:00 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_187/u1
2021/02/18 19:00:00 [INFO] - dbus: app_id:
2021/02/18 19:00:00 [INFO] - dbus: option types:3
2021/02/18 19:00:00 [INFO] - dbus: option multiple: 0
2021/02/18 19:00:00 [DEBUG] - dbus: select sources: found matching session /org/freedesktop/portal/desktop/session/1_187/u1
2021/02/18 19:00:00 [INFO] - wlroots: capturable output: Chimei Innolux Corporation model: 0x1409: id: 36 name: eDP-1
2021/02/18 19:00:00 [INFO] - xdpw: screencast instance 0x557597beeb90 has 1 references
2021/02/18 19:00:00 [INFO] - xdpw: 1 active screencast instances
2021/02/18 19:00:00 [INFO] - wlroots: output: eDP-1
2021/02/18 19:00:00 [INFO] - dbus: start method invoked
2021/02/18 19:00:00 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_187/u3
2021/02/18 19:00:00 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_187/u1
2021/02/18 19:00:00 [INFO] - dbus: app_id:
2021/02/18 19:00:00 [INFO] - dbus: parent_window:
2021/02/18 19:00:00 [DEBUG] - dbus: start: found matching session /org/freedesktop/portal/desktop/session/1_187/u1
2021/02/18 19:00:00 [DEBUG] - pipewire: registered event 0x557597b5ff10
2021/02/18 19:00:00 [INFO] - pipewire: stream state changed to "connecting"
2021/02/18 19:00:00 [INFO] - pipewire: node id is -1
2021/02/18 19:00:00 [INFO] - pipewire: stream state changed to "paused"
2021/02/18 19:00:00 [INFO] - pipewire: node id is 33
```

And the python script outputs:

```
session /org/freedesktop/portal/desktop/session/1_187/u1 created
sources selected
streams:
stream 4294967295
```

**Comment by danshick** [comment]
Hmmm, and I assume no screencast output from that script is shown.

So we know for sure that
- xdp is using xdpw for screencast requests
- xdpw is receiving cast requests and responding to them
- xdpw is able to communicate with pipewire

Would you be able to share pipewire logs (you can kill pipewire and run it manually in a shell, setting the environment variable `PIPEWIRE_DEBUG` to 3 or 4 would help as well)?

Also maybe make sure you aren't running into #79? Your symptoms are different, but this feels like a pipewire issue and that is the most recent one we've seen.

**Comment by mattikan** [comment]
Yeah, no screencast output from the script.
I checked, and there are no old pipewire configs hiding about.

Here's what pipewire's output looks like with debug level 3, trying the gUM Test Page's screen capture:

```
[I][000015894.508974][pipewire.c:458 pw_init()] version 0.3.21
[I][000015894.509212][main.c:80 load_config()] daemon 0x7ffe76882470: loading config '/etc/pipewire/pipewire.conf'
[I][000015894.529973][module-rtkit.c:522 set_nice()] main thread nice level set to -11
[I][000015894.530961][module-protocol-native.c:1146 impl_add_server()] protocol-native 0x55e1fd3ba2d0: Listening on 'pipewire-0'
[I][000015894.536343][impl-node.c:315 node_update_state()] (Dummy-Driver-28) creating -> suspended
[I][000015894.536434][context.c:893 pw_context_recalc_graph()] context 0x55e1fd3a3b20: busy:0 reason:register active node
[I][000015894.537306][main.c:300 do_exec()] exec got pid 11285 res:0 status:-46553058
[I][000015894.537446][main.c:469 main()] start main loop
[I][000015894.537583][main.c:287 do_exec()] exec /usr/bin/pipewire-media-session ''
[I][000015894.537690][module-portal.c:156 on_portal_pid_received()] Got portal pid 9211
[I][000015894.544089][pipewire.c:458 pw_init()] version 0.3.21
[I][000015894.548704][module-rtkit.c:508 idle_func()] processing thread made realtime
[I][000015894.551732][media-session.c:1807 sm_media_session_load_conf()] media-session 0x7fff95667980: loading config '/etc/pipewire/media-session.d/media-session.conf'
[I][000015894.552022][media-session.c:2320 main()]   'context.profile.modules' = 'default,rtkit'
[I][000015894.570675][module-rtkit.c:522 set_nice()] main thread nice level set to -11
[I][000015894.572512][local-socket.c:96 try_connect()] connecting to 'pipewire-0' runtime_dir:/run/user/1000
[I][000015894.572729][module-protocol-native.c:426 client_new()] server 0x55e1fd3ba740: security label not available
[I][000015894.572863][local-socket.c:96 try_connect()] connecting to 'pipewire-0' runtime_dir:/run/user/1000
[I][000015894.572979][media-session.c:2368 main()] enable: flatpak
[I][000015894.573033][media-session.c:2368 main()] enable: portal
[I][000015894.573042][module-protocol-native.c:426 client_new()] server 0x55e1fd3ba740: security label not available
[I][000015894.573540][media-session.c:2368 main()] enable: v4l2
[I][000015894.574384][media-session.c:1807 sm_media_session_load_conf()] media-session 0x7fff95667980: loading config '/etc/pipewire/media-session.d/v4l2-monitor.conf'
[I][000015894.576707][v4l2-utils.c:60 spa_v4l2_open()] v4l2: Playback device is '/dev/video0'
[I][000015894.584227][module-rtkit.c:508 idle_func()] processing thread made realtime
[I][000015894.687465][v4l2-utils.c:113 spa_v4l2_close()] v4l2: close
[I][000015894.689061][v4l2-utils.c:60 spa_v4l2_open()] v4l2: Playback device is '/dev/video1'
[I][000015894.689227][v4l2-utils.c:113 spa_v4l2_close()] v4l2: close
[I][000015894.689925][v4l2-utils.c:60 spa_v4l2_open()] v4l2: Playback device is '/dev/video2'
[I][000015894.690053][v4l2-utils.c:113 spa_v4l2_close()] v4l2: close
[I][000015894.690850][v4l2-utils.c:60 spa_v4l2_open()] v4l2: Playback device is '/dev/video3'
[I][000015894.690948][v4l2-utils.c:113 spa_v4l2_close()] v4l2: close
[I][000015894.691514][v4l2-udev.c:448 start_inotify()] start inotify
[I][000015894.691603][media-session.c:2368 main()] enable: suspend-node
[I][000015894.691639][media-session.c:2368 main()] enable: policy-node
[I][000015894.691938][module-access.c:172 context_check_access()] client 0x55e1fd3b7e00 has trusted pid 11285
[I][000015894.692054][module-access.c:235 context_check_access()] access 0x55e1fd3c63d0: client 0x55e1fd3b7e00 'unrestricted' access granted
[I][000015894.692563][module-access.c:172 context_check_access()] client 0x55e1fd3e3740 has trusted pid 11285
[I][000015894.692658][module-access.c:235 context_check_access()] access 0x55e1fd3c63d0: client 0x55e1fd3e3740 'unrestricted' access granted
[I][000015894.693985][v4l2-utils.c:60 spa_v4l2_open()] v4l2: Playback device is '/dev/video0'
[I][000015894.694404][v4l2-utils.c:113 spa_v4l2_close()] v4l2: close
[I][000015894.694582][v4l2-utils.c:60 spa_v4l2_open()] v4l2: Playback device is '/dev/video1'
[I][000015894.694677][v4l2-utils.c:113 spa_v4l2_close()] v4l2: close
[I][000015894.694721][v4l2-utils.c:60 spa_v4l2_open()] v4l2: Playback device is '/dev/video2'
[I][000015894.694926][v4l2-utils.c:113 spa_v4l2_close()] v4l2: close
[I][000015894.695026][v4l2-utils.c:60 spa_v4l2_open()] v4l2: Playback device is '/dev/video3'
[I][000015894.695104][v4l2-utils.c:113 spa_v4l2_close()] v4l2: close
[I][000015894.696126][v4l2-utils.c:60 spa_v4l2_open()] v4l2: Playback device is '/dev/video0'
[I][000015894.696241][v4l2-utils.c:113 spa_v4l2_close()] v4l2: close
[I][000015894.696563][impl-node.c:315 node_update_state()] (v4l2_output.pci-0000:00:14.0-usb-0:8:1.0-35) creating -> suspended
[I][000015894.696635][context.c:893 pw_context_recalc_graph()] context 0x55e1fd3a3b20: busy:0 reason:register active node
[I][000015894.696796][v4l2-utils.c:60 spa_v4l2_open()] v4l2: Playback device is '/dev/video2'
[I][000015894.696912][v4l2-utils.c:113 spa_v4l2_close()] v4l2: close
[I][000015894.697313][impl-node.c:315 node_update_state()] (v4l2_output.pci-0000:00:14.0-usb-0:8:1.2-37) creating -> suspended
[I][000015894.697469][context.c:893 pw_context_recalc_graph()] context 0x55e1fd3a3b20: busy:0 reason:register active node
[I][000015906.106546][module-protocol-native.c:426 client_new()] server 0x55e1fd3ba740: security label not available
[I][000015906.109385][module-protocol-native.c:282 handle_client_error()] protocol-native 0x55e1fd3ba2d0: client 0x55e1fd41b7b0 disconnected
[I][000015906.157238][module-protocol-native.c:426 client_new()] server 0x55e1fd3ba740: security label not available
[I][000015906.157321][module-access.c:172 context_check_access()] client 0x55e1fd41c0a0 has trusted pid 11290
[I][000015906.157348][module-access.c:235 context_check_access()] access 0x55e1fd3c63d0: client 0x55e1fd41c0a0 'unrestricted' access granted
[I][000015906.162780][module-portal.c:156 on_portal_pid_received()] Got portal pid 11290
[I][000015921.401585][module-protocol-native.c:282 handle_client_error()] protocol-native 0x55e1fd3ba2d0: client 0x55e1fd41c0a0 disconnected
[I][000015926.689787][module-protocol-native.c:426 client_new()] server 0x55e1fd3ba740: security label not available
[I][000015926.694329][module-access.c:172 context_check_access()] client 0x55e1fd4284c0 has trusted pid 11313
[I][000015926.694469][module-access.c:235 context_check_access()] access 0x55e1fd3c63d0: client 0x55e1fd4284c0 'unrestricted' access granted
[I][000015926.736098][module-protocol-native.c:426 client_new()] server 0x55e1fd3ba740: security label not available
[I][000015926.736201][module-access.c:172 context_check_access()] client 0x55e1fd4258c0 has trusted pid 11312
[I][000015926.736226][module-access.c:235 context_check_access()] access 0x55e1fd3c63d0: client 0x55e1fd4258c0 'unrestricted' access granted
[I][000015926.742192][module-portal.c:156 on_portal_pid_received()] Got portal pid 11312
[I][000015935.861251][impl-node.c:315 node_update_state()] (xdg-desktop-portal-wlr-42) creating -> suspended
[I][000015935.861413][context.c:893 pw_context_recalc_graph()] context 0x55e1fd3a3b20: busy:0 reason:node activate
[I][000015935.862072][module-protocol-native.c:426 client_new()] server 0x55e1fd3ba740: security label not available
[I][000015935.862152][module-portal.c:84 context_check_access()] portal 0x55e1fd3c28d0: portal managed client 0x55e1fd44c7c0 added
[I][000015935.862172][module-access.c:160 context_check_access()] client 0x55e1fd44c7c0: has already access: 'portal'
[I][000015935.862237][access-portal.c:175 handle_client()] access-portal 0x561d2524d2c0: portal managed client 44 added
[I][000015935.862324][access-portal.c:459 client_info_changed()] access-portal 0x561d2524d2c0: client 44 with app_id '' set to portal access
[I][000015935.862347][access-portal.c:226 set_global_permissions()] access-portal 0x561d2524d2c0: object 44 allowed:1
```

xdpw's output doesn't differ from the earlier.

**Comment by danshick** [comment]
This is the only relevant line from the pipewire logs:
 
```
[I][000015935.861251][impl-node.c:315 node_update_state()] (xdg-desktop-portal-wlr-42) creating -> suspended
```

I'm afraid I might need debug level 4. It gets really noisy really fast, unfortunately.

**Comment by mattikan** [comment]
Huh. Did as before - killed xdp, xdpw and pipewire. Ran pipewire with debug level 4, ran xdp and xdpw with the flags you gave earlier. Fired up the test page, and suddenly it works.
Completely at a loss as to what I could've changed to make it work. I didn't even restart the machine overnight.

I guess if the problem persists, I'll be sure to check in again with some more extensive pipewire logs. Thanks for your patience with me and my weird issue.

**Comment by danshick** [comment]
> I guess if the problem persists, I'll be sure to check in again with some more extensive pipewire logs. Thanks for your patience with me and my weird issue.

No problem. This is exactly what happened to OP as well. I wish I had a good answer for you.

**Comment by scottshotgg** [comment]
@mattikan
Are you aware of any changes that you have done. I am running into this same issue after previously having it working in Firefox.

**Comment by danshick** [comment]
> Are you aware of any changes that you have done. I am running into this same issue after previously having it working in Firefox.

@scottshotgg 
Lately, people have been reporting difficulties related to environment variables, specifically `WAYLAND_DISPLAY` not being set in time. Could you read through #116 and #117 and see if your answer lies in the troubleshooting done there?

**Comment by scottshotgg** [comment]
@danshick 

I certainly will do that this weekend and see if it resolves the issue. Thanks for the references and providing amazing support.

**Comment by danshick** [comment]
> I certainly will do that this weekend and see if it resolves the issue. Thanks for the references and providing amazing support.

@scottshotgg Happy to help. Come back if those issues don't clear up your problem and feel free to open a new one.

**Comment by tchebb** [comment]
I'm seeing what seems to be this issue currently, with Pipewire 0.3.22, xdp 1.8.0, xdpw 0.2.0, and a Sway/wlr Git build from April 9th. (I know I'm out-of-date, but I'm afraid I'll lose the repro if I upgrade and restart Sway).

Here are logs with `PIPEWIRE_DEBUG=4` from [xdpw](https://github.com/emersion/xdg-desktop-portal-wlr/files/6368936/xdpw.log), [xdp](https://github.com/emersion/xdg-desktop-portal-wlr/files/6368937/xdp.log), and [Pipewire](https://github.com/emersion/xdg-desktop-portal-wlr/files/6368938/pipewire.log).

**Comment by danshick** [comment]
> I'm seeing what seems to be this issue currently, with Pipewire 0.3.22, xdp 1.8.0, xdpw 0.2.0, and a Sway/wlr Git build from April 9th. (I know I'm out-of-date, but I'm afraid I'll lose the repro if I upgrade and restart Sway).
> 
> Here are logs with `PIPEWIRE_DEBUG=4` from [xdpw](https://github.com/emersion/xdg-desktop-portal-wlr/files/6368936/xdpw.log), [xdp](https://github.com/emersion/xdg-desktop-portal-wlr/files/6368937/xdp.log), and [Pipewire](https://github.com/emersion/xdg-desktop-portal-wlr/files/6368938/pipewire.log).

On a quick inspection, I can't say for certain that your issue doesn't have to do with your build of sway/wlroots, but I doubt it is making any difference.

I'm not seeinf anything in these logs that looks like an xdpw problem. My hunch is that pipewire is misconfigured. Are you running Arch Linux? If so, can you run `find /etc -iname *pacnew*` and post the output?

**Comment by tchebb** [comment]
My config files are all up to date:
```
$ sudo find /etc/ -iname '*.pacnew'
$ ls /etc/pipewire 
client.conf  client-rt.conf  media-session.d  pipewire.conf  pipewire-pulse.conf
$ pacman -Qkk pipewire
pipewire: 255 total files, 0 altered files
```

What particular lines in the output stand out to you? I can dig into this myself, but I've never done any work on Pipewire before and so don't know where the output starts to deviate from what it should look like.

**Comment by danshick** [comment]
It's not that I see something in the pipewire logs that looks wrong, but rather that our logs look normal and that leads me to believe the problem is between firefox and pipewire. There could be a format negotiation issue but I don't see any indication of that from a quick look.

I don't see anything out of the ordinary in any of the logs, but a number of people have been bitten by pipewire configs lately so I figured it was prudent to check.

I know you are reluctant to update, but that would be my next suggestion. I would either run a sway/wlroots release or the latest from master. Same for xdpw, pipewire, and Firefox.

**Comment by tchebb** [comment]
After upgrading everything, rebooting, and also installing `pipewire-media-session` (which appears to be packaged separately on Arch only as of Pipewire 0.3.23), Firefox screen sharing is working again. Thanks for your help! If the problem comes back, I'll try to gather more logs.

It looks like perhaps a link was never getting created between xdpw's source and Firefox's sink, going off how my new (working) logs differ from the ones I posted yesterday. That should be pipewire-media-session's job, right? It was running yesterday (you can see where it gets exec'd in `pipewire.log`), so not sure why it didn't create the link.

**Comment by danshick** [comment]
> It looks like perhaps a link was never getting created between xdpw's source and Firefox's sink, going off how my new (working) logs differ from the ones I posted yesterday. That should be pipewire-media-session's job, right? It was running yesterday (you can see where it gets exec'd in `pipewire.log`), so not sure why it didn't create the link.

Oh that's right. I forgot they're packaged separately now. I feel like `pipewire-media-session` should satisfy some meta-dependency of `pipewire`. I know they want it to be interchangeable, but they should probably require **something** to be installed. Oh well, it isn't my package.

We could probably mark it as an optional dependency for xdpw. I'll look into it.

**Comment by emersion** [comment]
I've added a small entry to this wiki about this.
