### ISSUE TITLE
Do we want to install the config.sample file with meson?

### ISSUE THREAD

**Issue by danshick** [emersion/xdg-desktop-portal-wlr#92]
Should meson drop config.sample in `$SYSCONFDIR/xdg-desktop-portal-wlr/` or elsewhere?

**Comment by maximbaz** [comment]
This could be helpful to some users 👍 

If the config file contains default values, and users can expect to just open that file, edit it, save and restart the app to apply the config, I would place it in `/etc/xdg-desktop-portal-wlr/config`.

If the config is just a sample, and you expect users to actually copy it somewhere else first, I would suggest placing it in `/usr/share/xdg-deskop-portal-wlr/examples/config`.

**Comment by columbarius** [comment]
Since we have the chooser_type "default" in #59 we could represent our default behaviour in a config file in /etc/xdg/xdg-desktop-portal-wlr/config, but some fields would stay empty. Additionally to the man page, we could add a commented config file, which describes the options, but the examples in the man page should be enough.

**Comment by danshick** [comment]
> I think using the default keyword, leaving output_name, max_fps, exec_before, exec_after all blank is reasonable for something we ship to /etc.
> Do ~/.config/... configs take precedence over /etc configs?
> And are they combined/merged, or do we just take the one with the highest precedence?

**Comment by emersion** [comment]
I'm not a fan of commented config files filled with empty fields. They make it hard to figure out what the user has changed, because the changes are drown in the comments and empty fields. They also duplicate documentation (which already exists in the man page).

**Comment by danshick** [comment]
Yeah, I think I agree with this, especially in our case where no config is strictly necessary.

So if we ship something, we should probably ship a sample to `/usr/share` or ship none at all and let users read the man pages.

**Comment by danshick** [comment]
I'm gonna close this. We can let package maintainers decide whether or not to ship a default config if they want.
