### ISSUE TITLE
Escape strings passed to the logger

### ISSUE THREAD

**Issue by danshick** [emersion/xdg-desktop-portal-wlr#94]
Now that some things being logged may come from config files or CLI arguments, we can't be sure we aren't logging any strings containing `%` characters. We should explicitly escape these as `%%` before logging here:

https://github.com/emersion/xdg-desktop-portal-wlr/blob/4489ea4bb6409046835e05c93ddc8e3f0aa2bcad/src/core/logger.c#L75

**Comment by emersion** [comment]
I don't understand. Can you explain what the issue is?

**Comment by danshick** [comment]
https://stackoverflow.com/questions/31408253/segmentation-fault-while-using-vfprintf
